### ISSUE TITLE
FreeIPA Authentication

### ISSUE THREAD

**Issue by hijak** [tomav/docker-mailserver#1024]
Hi

Has any one had any luck with authing with freeipa? is there a custom schema im missing ?

**Comment by hijak** [comment]
ive kinda cracked it ill have a guide somewhere

**Comment by sspreitzer** [comment]
FreeIPA is either its totally own API, which then enables also resolving AD trust users, etc.. Or it can be used as a normal LDAP provider. 

Solving the FreeIPA API could be done via a sssd running and serving PAM and NSS to the runnning contiainer daemons.

See my #1021 for Kerberos authentication feature request.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by padrino121** [comment]
@hijak Did you end up sorting this out, any feedback? Configuring LDAP now but having issues getting the filters right.
