### ISSUE TITLE
receiving SPAM (apparently) from inside

### ISSUE THREAD

**Issue by devel0** [tomav/docker-mailserver#1037]
## Context

From external ip address I can send email (through port 25) declaring from and to as internal domain without any authentication.

## Expected Behavior
When user declare an inside domain address on port 25 it should return error 553 5.7.1 to prevent spam from externals.

## Actual Behavior
Email from external ip can send internal-to-internal user without authentication on port 25.

## Possible Fix
force smtp auth on port 25 when user in domain

## Steps to Reproduce

If you try a simple telnet to your email server ( port 25 ) with follow

HELO example.com
MAIL FROM: user@example.com
RCPT TO: user@example.com
DATA

spam email

.

## Your Environment

```
tvial/docker-mailserver   latest              dac8816ec078        5 weeks ago         517MB
```

**Comment by dennisfischer** [comment]
What happens if you enable SRS? Instead of sending an internal -> internal mail the sender now tries to use SRS to send internal -> external? I'm pretty sure this should work since SRS is only "secure" if you have authentication in place. However, authentication seems bypassed by missing postfix configuration. Thus, you end up with an open relay - surely something that was not intended.

**Comment by devel0** [comment]
negative, it doesn't block email.
I tried

```
2018-11-24 13:02:11,684 INFO spawned: 'postsrsd' with pid 198
2018-11-24 13:02:11,685 INFO success: postsrsd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
postsrsd: started
```

but trying sending from outside using telnet SMTP approach

```
250 2.1.5 Ok
DATA
354 End data with <CR><LF>.<CR><LF>

this is stest

.
250 2.0.0 Ok: queued as 934A1300079B
quit
221 2.0.0 Bye
```

mail frmo inside to inside user still arrive without sender authentication.

**Comment by erik-wramner** [comment]
This sounds serious but it is an old issue. Do you still have the problem with the latest version?

When I try to reproduce it with my server I can't: "Message rejected due to: SPF fail - not authorized". Perhaps you were trying from a host that is listed as a valid sender for the domain and that the mail server thinks is trusted?

**Comment by devel0** [comment]
Actually I haven't domain active to test it (rdns, etc.. but from what I remember my smtp server was reached directly from inet without possible proxy (example)[https://github.com/devel0/linux-scripts-utils/blob/29c0fc8b6650e14f1e60388efae897b7ca02c7c3/fw.sh#L666].

If you can [this](https://github.com/tomav/docker-mailserver/tree/0fb4a6d082cc0a3c8a5d3ff6193d1032329d11d4) was the version I used that shows me the behavior described.

When I'll have time I'll try again with cloud service and I'll report here results, thanks you.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
