### ISSUE TITLE
Occasional cron daemon email failed logrotate 

### ISSUE THREAD

**Issue by george-angel** [tomav/docker-mailserver#1041]
docker-mailver: `tvial/docker-mailserver:release-v6.1.0`

I seem to be occasionally getting the follow email:

From: `root@mail.mydomain.com`
subject: `Cron <root@mail> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )`

Body:

```
/etc/cron.daily/logrotate:
pkill: pidfile not valid
Try `pkill --help' for more information.
```

Is there a logrotate inside the container? Isn't that redundant running in Docker?

Thanks

**Comment by trytuna** [comment]
I‘ve got the same issue

**Comment by jrd** [comment]
Seems like a race condition on a process and its pid file...

**Comment by nicotillmann** [comment]
Same problem here:
docker-mailver: tvial/docker-mailserver:latest (but we build our container a year ago.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
