### ISSUE TITLE
Configuration of SpamAssassin evasive measures does not work(?)  

### ISSUE THREAD

**Issue by kortenkamp** [tomav/docker-mailserver#1045]
## Context
A lot of spam is coming through that has a spam rating between 4 and 6. SpamAssassin apparently works, as the Spam rating headers are added to the mails. In order to reduce spam, I lowered the SA_KILL value to 4. 

## Expected Behavior
No mail with a rating above 4 should be accepted.

## Actual Behavior
I still receive mails with spam rating about 5

## Possible Fix
No idea. And I don't even have a clue how to debug this properly.

## Steps to Reproduce
1. Change the SA_KILL value in `docker-compose.yml` to 4

## Your Environment

* Amount of RAM available: enough.
* Mailserver version used: latest
* Docker version used: Docker version 17.05.0-ce, build 89658be
* Environment settings relevant to the config: 
```
    - ENABLE_FAIL2BAN=1
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - SSL_TYPE=letsencrypt
    - TLS_LEVEL=intermediate
    - SA_TAG=-2
    - SA_TAG2=3
    - SA_KILL=4
    - ONE_DIR=1
    - ENABLE_POSTGREY=1
    - POSTGREY_DELAY=600
```

**Comment by johansmitsnl** [comment]
DId you properly shutdown/startup with the new env variable?
What does the log show?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
