### ISSUE TITLE
Set smtp_bind_address

### ISSUE THREAD

**Issue by ItsEcholot** [tomav/docker-mailserver#1058]
Is it possible to change the option smtp_bind_address in the master.cf?

I would like to change the configuration to the following:
```
smtp      unix  -       -       y       -       -       smtp
        -o smtp_bind_address=xxx.xxx.xxx.xxx
relay     unix  -       -       y       -       -       smtp
        -o smtp_bind_address=xxx.xxx.xxx.xxx
        -o smtp_fallback_relay=
```

**Comment by ItsEcholot** [comment]
I tried putting everything on one line and the following error gets put out into the console on startup:

```
postconf: fatal: missing '=' after attribute name: "smtp      unix  -       -       -       -       -       smtp -o smtp_bind_address=xxx.xxx.xxx.xxx",
postconf: fatal: missing '=' after attribute name: "relay     unix  -       -       -       -       -       smtp -o smtp_bind_address=xxx.xxx.xxx.xxx -o smtp_fallback_relay="
```

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, open a PR based on the current master branch so we can review it.
