### ISSUE TITLE
Integrate support for EFF's "StartTLS Everywhere" project

### ISSUE THREAD

**Issue by nogweii** [tomav/docker-mailserver#1080]
## Context
Prevent downgrade attacks in SMTP by including a list of email domains that support StartTLS and ensuring that Postfix proactively looks for that support.

## Expected Behavior
For a given server in that list, StartTLS is *always* used and MitM attackers who strip out advertising that support over clear-text SMTP are unsuccessful.

See their Github repo for more information: https://github.com/EFForg/starttls-everywhere/

**Comment by johansmitsnl** [comment]
Could you provide a PR for this?

**Comment by LukeMarlin** [comment]
Looking at http://www.postfix.org/TLS_README.html, I see no way of achieving that feature with the current configuration options. Maybe an add-on to postfix could achieve this, however it looks out of the scope of that project

**Comment by erik-wramner** [comment]
My view is that we should close this until it is supported in Postfix. It is a nice feature, but I would be vary of running it if it is not in upstream.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
