### ISSUE TITLE
Support dovecot for sasl auth

### ISSUE THREAD

**Issue by everflux** [tomav/docker-mailserver#1102]
The template configuration is prepared to use dovecot as sasl provider.
But there is no way to keep this configuration, in https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L695 the sasl auth is disabled if ENABLE_SASLAUTHD is not set to 1, but if that is set to 1, the dovecot sasl configuration gets overriden with the cyrus saslauth setup.

Suggestion: Add ENABLE_DOVECOT_SASL variable, avoiding cyrus setup and keeping the sasl configuration as provided in the postfix main.cf

**Comment by johansmitsnl** [comment]
Could you provide a pr for this?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
