### ISSUE TITLE
[Security Issue] docker-compose files use image from docker hub instead of building from dockerfile

### ISSUE THREAD

**Issue by K-marad** [tomav/docker-mailserver#1116]
I think the title is self explanatory, the docker-compose distributed files on github should use the local image built from the local dockerfile, and not download the image on the dockerhub.

This can lead to important security breaches !

Also editing configuration files in target/ locally is useless since rebuilding the container will only download the image again from dockerhub.

**Comment by johansmitsnl** [comment]
The user can always decide if they want to build their own image or not.
The compose files are example files for people that want to run it from the docker hub.

By saying that Docker hub can't be trusted is a big statement. If users are that paranoid they can build their own images. Other that can accept this rist can use the images from docker hub. You don't use any images from docher hub? You build everything (even your OS) yourself? I can agree that there is a certain risk having images build at docker hub, but to many users/compaies this is an acceptable risk (by having trust in docker hub).

The configuration files need to be in a specific state for the startup script to manipulate them based on the env variable. If the files are not in that state the startup script can't modify them and would result in a broken system. But why do you want to edit configuration files of a running container? This breaks down the use of a git repo with commited config files and env variable to manage functionality.

**Comment by K-marad** [comment]
Do you know a lot of github docker-compose projects that point to dockerhub instead of the shipped dockerfile ? That's the first one I see.

Then I use dockerhub for images coming from trusted companies. And I don't trust people "by default".
So yes I'm paranoid enough to prefer to build images myself than to run untrusted code on my machines.

Now there is nothing personal, and I sincerely have faith that these images aren't compromised, but it seems important to me that this project at least talks about that when building from the sources pulled from git you actually don't build, but download the images from elsewhere.
And maybe provide docker-compose files to build the image locally.

**Comment by johansmitsnl** [comment]
There are several repos that have compose files that don't build but use images from docker hub:
* https://github.com/jwilder/nginx-proxy/blob/master/docker-compose.yml
* https://github.com/bitnami/bitnami-docker-mariadb/blob/master/docker-compose.yml

Etc... People that have the skills will know how to make changes to build their own. 

In the wiki there are options to make overrides to certain parts of the config that will apply with a simple restart. Example https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration

If there are performance improvements that can be applied it is apriciated to provide a pull request so that everyone can benefit from this. 

If you look at mariadb or nginx images if you want to modify default behaviour you have to rebuild it to like any other project I have used. Working with volumes for the config I understand what you mean but it will break future updates and makes it hard to support. But maybe you have projects you can reference to for us to see how they solved the configuration issues. 

Currently this project is based on the current structure and making changes would have a great impact. Feel free to provide a pull request to coloborate your ideas and I will review them and merge if they improve the project.
