### ISSUE TITLE
Consider disabling SMTPUTF8

### ISSUE THREAD

**Issue by andreasgerstmayr** [tomav/docker-mailserver#1117]
Some mails bounce with `status=bounced (SMTPUTF8 is required, but was not offered by host mail.xxxxxxx.net[/var/run/dovecot/lmtp])`

Turns out postfix advertises SMTPUTF8 support, but [dovecot LMTP cannot handle SMTPUTF8 at the moment](https://dovecot.org/pipermail/dovecot/2018-September/112887.html), therefore postfix bounces the mails (see this [stackexchange question](https://unix.stackexchange.com/questions/320091/configure-postfix-and-dovecot-lmtp-to-receive-mail-via-smtputf8)).

imho we should disable advertising SMTPUTF8 support in postfix, but the only concern is that this could break existing setups which use postfix only for sending SMTPUTF8 mails.

What do you think?

**Comment by johansmitsnl** [comment]
If you make it optional why not? Can you provide a pull request?

**Comment by johansmitsnl** [comment]
Good argument, can you add a test with a email that is broken and then add the fix that will make the test pass?
Happy to merge the request if you could make one.

**Comment by andihit** [comment]
ok, will do in the next days

**Comment by andihit** [comment]
Sorry for the late reply. After reconsidering it again today I think I can't write a proper unit test for this case. With this setting the mailserver still can't accept SMTPUTF8 mails, but it will advertise this fact to the (other) sending mailserver instead of receiving the mail, forwarding it to dovecot and bouncing it there (as dovecot LMTP can't handle SMTPUTF8).

The idea would be that the sending mailserver recognizes that our mailserver can't handle SMTPUTF8 and maybe performs a conversion to support non-SMTPUTF8-mailservers. Unfortunately I couldn't find evidence if mailservers perform that way or not. If not, the end result is the same anyway - the mail stack of this docker image can't handle SMTPUTF8 and is therefore not accepting/bouncing mails with SMTPUTF8.

**Comment by tronicum** [comment]
until that,  "smtputf8_enable = no". Its not acceptable to accept mails and then bounce them back. that turn you into a spam trap.

**Comment by erik-wramner** [comment]
It appears SMTPUTF8 support is still lacking, see http://dovecot.2317879.n4.nabble.com/SMTPUTF8-support-td67266.html. In addition it is not enough to make postfix and dovecot support it, all the milters must work with UTF8 as well! Probably non-trivial.

Also https://unix.stackexchange.com/questions/320091/configure-postfix-and-dovecot-lmtp-to-receive-mail-via-smtputf8 suggests `smtputf8_enable = no`.

I think that is the way to go. The question is how to write a reasonable test for it.

**Comment by erik-wramner** [comment]
Fixed.

**Comment by VanVan** [comment]
Feel free to vote for the request to add support for UTF8 on Dovecot LMTP on the TODO List
 https://github.com/dovecot/core/pull/188
