### ISSUE TITLE
I need help about spam relay

### ISSUE THREAD

**Issue by unomind** [tomav/docker-mailserver#1136]
I've monitor container log. And got this:
```
mailserver | Feb 27 17:02:19 vps postfix/smtpd[13005]: C33F9B98A: client=unknown[172.19.0.1]
mailserver | Feb 27 17:02:22 vps postfix/cleanup[13028]: C33F9B98A: message-id=<>
mailserver | Feb 27 17:02:22 vps opendkim[175]: C33F9B98A: no signing table match for 'spameri@tiscali.it'
mailserver | Feb 27 17:02:22 vps opendkim[175]: C33F9B98A: no signature data
mailserver | Feb 27 17:02:22 vps postfix/qmgr[937]: C33F9B98A: from=<spameri@tiscali.it>, size=395, nrcpt=1 (queue active)
mailserver | Feb 27 17:02:27 vps postfix/smtpd[13005]: disconnect from unknown[172.19.0.1] ehlo=1 mail=1 rcpt=1 data=1 rset=1 quit=1 commands=6
mailserver | Feb 27 17:02:28 vps postfix/smtpd[13063]: connect from localhost[127.0.0.1]
mailserver | Feb 27 17:02:28 vps postfix/smtpd[13063]: BC73CB97A: client=localhost[127.0.0.1]
mailserver | Feb 27 17:02:28 vps postfix/cleanup[13028]: BC73CB97A: message-id=<20190227100228.BC73CB97A@vps.sumarsono.com>
mailserver | Feb 27 17:02:28 vps postfix/qmgr[937]: BC73CB97A: from=<spameri@tiscali.it>, size=626, nrcpt=1 (queue active)
mailserver | Feb 27 17:02:28 vps postfix/smtpd[13063]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
mailserver | Feb 27 17:02:28 vps amavis[19561]: (19561-05) Passed CLEAN {RelayedOutbound}, LOCAL [172.19.0.1]:56701 <spameri@tiscali.it> -> <spameri@tiscali.it>, Queue-ID: C33F9B98A, mail_id: 0GXTLFWpptPO, Hits: 1.965, size: 358, queued_as: BC73CB97A, 5864 ms
mailserver | Feb 27 17:02:28 vps postfix/smtp[13040]: C33F9B98A: to=<spameri@tiscali.it>, relay=127.0.0.1[127.0.0.1]:10024, delay=9.2, delays=3.4/0.01/0.01/5.9, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as BC73CB97A)
mailserver | Feb 27 17:02:28 vps postfix/qmgr[937]: C33F9B98A: removed
mailserver | Feb 27 17:02:44 vps postfix/smtp[13064]: BC73CB97A: to=<spameri@tiscali.it>, relay=etb-2.mail.tiscali.it[213.205.33.61]:25, delay=15, delays=0/0.02/15/0.75, dsn=2.0.0, status=sent (250 2.0.0 hm2d1z01w0ARWv701m2eun mail accepted for delivery)
mailserver | Feb 27 17:02:44 vps postfix/qmgr[937]: BC73CB97A: removed
```

How to prevent that spam relay?
Thanks

**Comment by johansmitsnl** [comment]
`mail accepted for delivery` does it gets relayed outside or is it being delivered to a mailbox?
Post your relevant config.

**Comment by unomind** [comment]
the mail was `status=sent`.
Here my config https://gist.github.com/unomind/64a745e72b29cba32227b5621c9a3134

**Comment by johansmitsnl** [comment]
Config seems ok, no idea at the moment

**Comment by unomind** [comment]
thank you

**Comment by flyingdutchman31** [comment]
I was also wondering how to prevent email thats not from my domain being relayed through the server. After some googling I saw that postfix has a setting called relay_domains where you can set which domains maybe relayed. How can I set this in the container?

**Comment by unomind** [comment]
@flyingdutchman31 any update?

**Comment by flyingdutchman31** [comment]
I disabled the mailserver, because I saw mail incomming abusing my domain. Cause of time I didnt spend any time on it  since then.

**Comment by erik-wramner** [comment]
@unomind is this still a problem with the latest version, or should we close the issue? If the server is an open relay that is quite serious and then it would be nice with more data (logs, examples of messages, your SPF configuration if any and so on). I haven't seen this on my server, but who knows?

**Comment by flyingdutchman31** [comment]
I havent tried it again because of time. I probably made a mistake during install/setup. Best to close this issue

Groet,

Christian
________________________________
Van: Erik Wramner <notifications@github.com>
Verzonden: Monday, August 5, 2019 6:42:14 PM
Aan: tomav/docker-mailserver <docker-mailserver@noreply.github.com>
CC: flyingdutchman31 <Christian.douma@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [tomav/docker-mailserver] I need help about spam relay (#1136)


@unomind<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Funomind&data=02%7C01%7C%7Cccaa0efcbf14438ba24008d719c3df44%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637006201357734685&sdata=%2FXpVp33pdPSp%2FG%2FLC3pz6agX%2BiIRbXoEsd6PsVlk1LU%3D&reserved=0> is this still a problem with the latest version, or should we close the issue? If the server is an open relay that is quite serious and then it would be nice with more data (logs, examples of messages, your SPF configuration if any and so on). I haven't seen this on my server, but who knows?

**Comment by erik-wramner** [comment]
OK. Please re-open or create a new issue if this happens again.

**Comment by therealklanni** [comment]
This is still happening. I just set up mailserver and this address "spameri@tiscali.it" is somehow being allowed to relay on my server (even though it denies all other relay attempts).
