### ISSUE TITLE
Cannot delete mailbox using admin tools

### ISSUE THREAD

**Issue by andig** [tomav/docker-mailserver#1155]
I'm a total noob with anything mail-related. This wonderful image has been running for a couple of months and now I'd like to delete from (existing) mailboxes:

    admin@NAS:~/mailadmin$ sudo ./setup.sh email del foo@bar
    sed: can't read /tmp/docker-mailserver/postfix-virtual.cf: No such file or directory
    Aliases for foo\@bar couldn't be deleted in /tmp/docker-mailserver/postfix-virtual.cf. 1
    

## Your Environment

Running uptodate image. Docker env:

    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/fullchain.pem
    - SSL_KEY_PATH=/tmp/ssl/privkey.pem

**Comment by tomav** [comment]
I don't use `setup.sh` because using it, you can't understand what you're actually doing.
To remove a mail acount, delete the line containing your user in `postfix-accounts.cf`, and delete the matching folder in `/var/mail/$domain/$user`. Then restart.
If it's an alias, just remove it from from `postfix-virtual.cf` and restart.

Note: you can also do things on the fly, the generated files used by postfix are under `/etc/postfix`, check out their documentation is you want to know more.

**Comment by Rillke** [comment]
I believe this issue should not have been closed. Today, I stumbled over the very same issue.

```
$ ./setup.sh
Usage: ./setup.sh [-i IMAGE_NAME] [-c CONTAINER_NAME] <subcommand> <subcommand> [args]

OPTIONS:
...
SUBCOMMANDS:

  email:

...
    ./setup.sh email del <email>
...
```

If `setup.sh` is not able to properly delete accounts, it should not pretend to. It might just point to relevant documentation.

A bit of searching reveals that [`delmailuser`](https://github.com/tomav/docker-mailserver/blob/master/target/bin/delmailuser) is invoked in the Container where it fails because `$ALIAS_DATABASE` does not exist - maybe because I haven't defined any aliases. As a consequence, you will never be prompted with `Do you want to delete the mailbox as well(all mails will be removed)?(y/n)` leaving the mail boxes and you have to delete them manually like suggested in the previous comment https://github.com/tomav/docker-mailserver/issues/1155#issuecomment-514617786

**Comment by erik-wramner** [comment]
Perhaps we should remove the option or at least the option to also delete the mailbox. Feel free to improve the documentation in the Wiki for this!
