### ISSUE TITLE
Allow use of custom content filters

### ISSUE THREAD

**Issue by brainkiller** [tomav/docker-mailserver#1157]
Instead of expanding the docker image with all possible content filters I would like to see the possibility of configuring postfix to foward mails to another IP+port for content filtering and accept it on another port for further processing of the mail chain.

I acknowledge that this could endanger the security of the mailserver if the firewall is not setup correctly to ensure that the receiving port is not exposed to the outside world.

In my specific case I would like to use this feature to include my existing popfile installation for mail filtering. I like the management part of it so I prefer to continue to use it.

It would accept the mails from postfix on a specific IP and port and after processing sent it back it postfix on a specific port.

At this moment I have no clue where this should be best integrated in the scripting. If you could give some pointer I could try to create a pull request.

**Comment by erik-wramner** [comment]
Not sure if it makes sense (I'm no expert in this and I haven't researched it), but wouldn't it be easier to just connect to the content filtering running on the other host instead? If I remember correctly we're using domain sockets here, but on another server I think I used an IP address and port to get around SELinux issues. If you're lucky you can get what you want simply by tweaking the configuration.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
