### ISSUE TITLE
Postfix rejects valid sender with SPOOF_PROTECTION env variable set to 1

### ISSUE THREAD

**Issue by daiwai** [tomav/docker-mailserver#1168]
## Context
I have a small installation which had only one address configured. After adding a second address I received the following error message when trying to send a message from the second address while also being authenticated as that second user:

`May 15 11:16:53 mail postfix/smtpd[1053]: NOQUEUE: reject: RCPT from unknown[0.0.0.0]: 553 5.7.1 <sender@example.com>: Sender address rejected: not owned by user sender@example.com; from=<sender@example.com> to=<user@example.com> proto=ESMTP helo=<[0.0.0.0]>
`

## Expected Behavior
The message should pass if the authenticated sender matches the from address

## Actual Behavior
The message is rejected, see log message above.

**Comment by erik-wramner** [comment]
Can you elaborate on how you are sending the message, please? Ideally with a reproducible test case? And have you had an alias for the second user before?

I had a similar issue and it turned out to be a problem with aliases. One user owned the address for another (newly added) user through an alias. It took some time to figure that out.

**Comment by erik-wramner** [comment]
@daiwai please get back with some details so that we can try to reproduce this, not least the image you are running (latest, stable or a specific release). If we don't hear from you I'll close this.

**Comment by erik-wramner** [comment]
Closed due to inactivity. Please reopen or file a new issue if the problem persists.
