### ISSUE TITLE
Sieve Redirect Error

### ISSUE THREAD

**Issue by soliddash** [tomav/docker-mailserver#1179]
Have setup a simple sieve file:

redirect "x@domain.com";
keep;

When testing I do not get the test emails.  In the sieve.log for the user being emailed you get "failed to redirect message to <x@domain.com>: Failed to execute sendmail (temporary failure).

**Comment by soliddash** [comment]
Seems this was a permission issue that's crept in - can you put this in a sanity check script on startup?

Found fix in #1029, solution was todo this inside docker instance:

chgrp postdrop /var/spool/postfix/maildrop
chgrp postdrop /var/spool/postfix/public

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
