### ISSUE TITLE
Amavis can't access to user emails

### ISSUE THREAD

**Issue by iDevPro** [tomav/docker-mailserver#1188]
`sa-learn` under Amavis user failed with permission errors.

## Context
`sa-learn --spam /var/mail/domain/username/.Junk/{cur,new}`

## Expected Behavior
`Learned tokens from 622 message(s) (622 message(s) examined)`

## Actual Behavior
`
archive-iterator: no access to /var/mail/domain/username/.Junk/cur: Permission denied at /usr/share/perl5/Mail/SpamAssassin/ArchiveIterator.pm line 586.
archive-iterator: no access to /var/mail/domain/username/.Junk/cur: Permission denied at /usr/share/perl5/Mail/SpamAssassin/ArchiveIterator.pm line 828.
archive-iterator: no access to /var/mail/domain/username/.Junk/new: Permission denied at /usr/share/perl5/Mail/SpamAssassin/ArchiveIterator.pm line 586.
archive-iterator: no access to /var/mail/domain/username/.Junk/new: Permission denied at /usr/share/perl5/Mail/SpamAssassin/ArchiveIterator.pm line 828.
archive-iterator: unable to open /var/mail/domain/username/.Junk/cur: Permission denied
archive-iterator: unable to open /var/mail/domain/username/.Junk/new: Permission denied
Learned tokens from 0 message(s) (0 message(s) examined)
`

## Possible Fix
`sa-learn --spam /var/mail/domain/username/.Junk/{cur,new} --dbpath /var/mail-state/lib-amavis/.spamassassin` [workaround]

## Steps to Reproduce
1. docker exec -it mail_server /bin/bash
2. su amavis -c /bin/bash
3. sa-learn --spam /var/mail/domain/username/.Junk/{cur,new}

## Your Environment
* Amount of RAM available: 2G
* Mailserver version used:  tvial/docker-mailserver:latest
* Docker version used: Docker version 18.06.1-ce, build e68fc7a

**Comment by erik-wramner** [comment]
The workaround is already documented in https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips, which uses `--dbpath` to point to the location of the database. If that works then amavis must have access to the user e-mails and the error must be from failing to access the database in the default location? Otherwise it should not be possible to analyze the e-mails by adding the `--dbpath` option.

Looking at the FAQ I think this is working as designed and that the workaround is the way to go.
