### ISSUE TITLE
dovecot critical cve-2019-11500

### ISSUE THREAD

**Issue by time4tea** [tomav/docker-mailserver#1250]
https://www.cvedetails.com/cve/CVE-2019-11500/

**Comment by erik-wramner** [comment]
That was a rather short problem description, but #1242 fixed CVE 2019-11500. Provided that you are using "latest" you should be safe. The CVE is not fixed in the old versions and we won't do that as it would break backwards compatibility. We will create a new stable release and new numbered releases, though.
