### ISSUE TITLE
Reject some recipient adresses while using catchall on a domain

### ISSUE THREAD

**Issue by vortex852456** [tomav/docker-mailserver#1281]
I want to config this: https://www.anginf.de/?p=328

Whats the best way to accomplish that with docker-mailserver?

I don't nesessarely need a detailed instruction. Just a hint whats the "clean" way would help me a lot since I'm new to docker.

**Comment by erik-wramner** [comment]
I'm no expert here, but I think you can add the file to the `config` directory which is already mapped into the container. Then you can override the `smtpd_recipient_restrictions` setting in `config/postfix-main.cf`. The settings in that file will override the other default/generated settings.

**Comment by Undercover1989** [comment]
Thanks @erik-wramner, this helped a lot and is working. These were my steps:

First I created a file name "postfix-recipient-block" with following content:
`noreply@domain.tld REJECT`

Then I used the command "postmap /tmp/docker-mailserver/postfix-recipient-block" inside the container which generated ./config/postfix-recipient-block.db

Then I added the following line to ./config/postfix-main.cf:
`smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org, reject_rbl_client bl.spamcop.net, hash:/tmp/docker-mailserver/postfix-recipient-block`

This is not as clean as I would like it, because I have to manually use postmap after every change on postfix-recipient-block and smtpd_recipient_restrictions are now "hardcoded" (it would be better if only the new content (`, hash:/tmp/docker-mailserver/postfix-recipient-block`) would be automatically added.

**Comment by Undercover1989** [comment]
Found out if I use "texthash:" instead of "hash:" I don't have to call postmap anymore.

I think to dynamically add the entry for `texthash:/tmp/docker-mailserver/postfix-recipient-block.cf` to the `smtpd_recipient_restrictions` I would have to rebuild the image myself. Or does anyone have an idea?

**Comment by erik-wramner** [comment]
Well, personally I would just add the lines above to `postfix-main.cf` as not getting changes to that specific option feels like a lesser evil to me, but otherwise you could either build the image yourself or add a `docker exec` with the patch to your startup script.

If you want you could write a PR that adds code to the start script that checks for a shell script (user-patches.sh?) in the config folder and runs it if it is there some time late (after other changes but before starting the daemons). That would make it possible to run custom user-specific code without building a new image and might be useful for others as well.

**Comment by togo42** [comment]
It should just work without changing **postfix-main.cf** and extra **postfix-recipient-block.cf** file. You can just use **./setup.sh email restrict add receive noreply@domain.tld**

**Comment by vortex852456** [comment]
Thanks!

**Comment by radicand** [comment]
For those that follow using this in a k8s environment, the option using `postfix-main.cf` and `postfix-recipient-block.cf` as mounts is straightforward and works well. Just add those new files to your ConfigMap, then mount them (similar to the other postfix files mounted from there).

**Comment by neagix** [comment]
> It should just work without changing **postfix-main.cf** and extra **postfix-recipient-block.cf** file. You can just use **./setup.sh email restrict add receive [noreply@domain.tld](mailto:noreply@domain.tld)**

I used this approach and it did indeed work 👍
