### ISSUE TITLE
Able to send mails but unable to receive mails/replies to sent mails

### ISSUE THREAD

**Issue by Johnpojohn** [tomav/docker-mailserver#1295]
Hi there,

I installed the container using the instructions on a Synology server and the container booted up fine. I generated the dkim keys and an account. I set up the container to work at mail.domain.com and created my user account. 

I can send emails fine to gmail and mail-tester.com (which says my DKIM signature is invalid, although I copied it from the .txt file as per the instructions). When logging in to my account with thunderbird, name@domain.com works but name@mail.domain.com does not. If I send a mail using it, the mail will be received as sent from name@domain.com, but mail-tester says the mail "appears to be sent" from name@mail.domain.com

Finally, I cannot receive e-mails to either name@domain.com or name@mail.domain.com. The container logs show no indication of a received email and the sender address receives no failure report either.

What am I doing wrong?

**Comment by erik-wramner** [comment]
Where are those instructions you refer to? Are they part of this project's wiki?

Local users such as name@mail.domain.com are not used, all users are virtual. There should be no local users defined; the accounts file should not contain any name@mail.domain.com users. Furthermore you should never send mail to or try to connect as anything@mail.domain.com. The users are defined on the domain level, not on the host. There may be exceptions for local use, but personally I handle them with aliases instead and stick to virtual accounts.

That means that what you get with Thunderbird is correct. The part about "appears to be sent" can be fixed though I can't say what is wrong without more data. Also your failure to receive messages is a problem, but if there are no logs the problem is probably outside docker-mailserver (firewalls, wrong MX records in the DNS, ...).

**Comment by Johnpojohn** [comment]
I mean the instructions from the readme.md file (section "usage"). The issue with receiving mails was indeed the firewall, its working now. Just need to get that DKIM fixed and I'm good to go! :)

**Comment by Johnpojohn** [comment]
Which...was actually just a matter of waiting for the DNS to update. Everything is working, thanks so much!
