### ISSUE TITLE
success with SSL but not with TLS

### ISSUE THREAD

**Issue by sebastienPoussard** [tomav/docker-mailserver#1316]
Hi,
I started my docker-mailserver opening ports 25,143, 587,993.
i try to connect with an account with an android application.
when i open the port 465 and try to open an account with a client on port 465 therefore with SSL encryption i do not have any problem.
when i close the port 465 and try to open an account with a client on port 587 therefore with TLS i do not succeed. errors like : "cannot connect to server"
i do not understand.
when i try manual connection with "nc <server> 465" i do have a response, it seems to work.
i guess i doesn't have enough experience to debug this. 

Do you have any ideas where the problem might come from ?

Best regards.

**Comment by erik-wramner** [comment]
Your explanation is a bit confused, so perhaps you have simply missed something when making changes. I would suggest starting with both 465 and 587 open in your compose file. Start the container and verify with nc or telnet or some other program that the ports are open on the host, so that it is possible to connect to them. Then try to connect with your e-mail client to both and see what happens. Check the logs (docker-compose logs) as well as the error messages from the client.

**Comment by sebastienPoussard** [comment]
erik,
my confusion came from the dockerhub 
````
465 SSL Client email submission
587 TLS Client email submission
````
I thought 465 was only using SSL protocol but when i did some test with openssl client i realised it was instead using TLS protocol.
Best regards
