### ISSUE TITLE
opendkim howto ?

### ISSUE THREAD

**Issue by auguster** [tomav/docker-mailserver#132]
I mounted the `/etc/opendkim` folder on the host to ensure persistence of the DKIM signature, I set the corresponding public key in the DNS using content from `/etc/opendkim/keys/<my domain>/mail.txt`. But while testing it I noticed the mail weren't signed.

In fact, I noticed this in my logs:
`opendkim: /etc/opendkim.conf: refile:/etc/opendkim/TrustedHosts: dkimf_db_open(): No such file or directory`

It coming from:
`/etc/init.d/opendkim start` ([L292 of start-mailserver.sh](https://github.com/tomav/docker-mailserver/blob/master/start-mailserver.sh#L292))

Is there anything specific to do to enable DKIM ?

EDIT: BTW, I'm not familiar with DKIM but shouldn't there be an `/etc/opendkim/TrustedHosts` file ? It seems to be missing.

**Comment by auguster** [comment]
Ok, I got it to work by manually adding the `/etc/opendkim/TrustedHosts` with the correct content. It was easier than I thought.

I noticed it's not part of the opendkim initialization process of the script I guess it should be. I will make a fix and a PR soon.

**Comment by 00angus** [comment]
@auguster sorry for the late reply... anyway...
I've that same setup.
I've copied the content from a first run of the container and made it persistent, that way all the needed file are ok :) 
I've added a commit to the v2 branch that handles host based opendkim configurations.
If interested I can merge it on master, take a look and let me know :)

**Comment by auguster** [comment]
@00angus  Don't worry, I was supposed to make a PR soon anyway ^^

I think the file should be generated by the start script if missing. It should just contain `127.0.0.1` and `localhost` anyway. Manually copying files feels `manual` and error proned if not well documented (or if the documentation gets ignored).

I still hope on making a quick fix soon if my schedule allows.

**Comment by 00angus** [comment]
[Here](https://github.com/tomav/docker-mailserver/blob/v2/target/start-mailserver.sh#L94) is the patch take a look if you want.

The only manual part is the initial creation of the config that should be made persistent. It's sufficient to add a /usr/local/bin/ script and call it like we call the script for the generation of ssl certs.

**Comment by auguster** [comment]
From what I read that script doesn't create `/etc/opendkim/TrustedHosts` if the file is missing.

By the way, this script doesn't add a new DKIM for a new domain while `/etc/opendkim/TrustedHosts` exists. So I would say the [current version of the script](https://github.com/tomav/docker-mailserver/blob/master/start-mailserver.sh#L69) is more powerfull in term of flexibility. It's just missing a check for `/etc/opendkim/TrustedHosts`'s existence.

**Comment by tomav** [comment]
Yep, and this has been fixed in v2.
https://github.com/tomav/docker-mailserver/blob/v2/Dockerfile#L39

**Comment by auguster** [comment]
Nop, that doesn't change a thing. If I mount an empty folder from the host to `/etc/opendkim/`, to have it populated with persistent DKIM stuff. Then the `TrustedHosts` file is not there and won't be recreated by `start-mailserver.sh`. That's what this issue is all about.

**Comment by 00angus** [comment]
Maybe I'm getting confused :)
Let me clarify:

1. I want to generate - one time - opendkim data/config ? Then I **cannot** mount a host volume on /etc/opendkim **to generate** that data with **that** image (v2 or master in this case is the same). 
By mounting an empty host volume into /etc/opendkim you are overwriting the image current content, and that includes the TrustedHosts file. That file will be missing. Currently you have to **manual** copy that data out and that manual thing is what **we want to remove** (I think you would agree on that - at least I hope :) );
2. I want to use an already generated data/config for opendkim (like I already have and - I hope - you already have): In **that** case you can safely use v2 branch because of the patch already merged, that would copy the data from /tmp/docker-mailserver/opendkim (if I remember correctly)

I know that the current setup for opendkim could be reworked as initially was _NOT_ intended for importing external data/config. My current patch on v2 is my **temporary** workaround but a more complete and integrated solution would be needed.

We could - as an example - generate all the needed config/data during start-mailserver.sh startup (included the TrustedHosts file) and then at each startup if a config is already available do not generate anything else ... or something like that. That way our host volume could safely be mounted on /etc/opendkim and everything should work. 
What do you think about it?

**Comment by auguster** [comment]
No your not not getting confused, that's exactly the behavior I'm looking for.

**Comment by 00angus** [comment]
@tomav what do you think about it? Could you add a "feature" label to the issue so to not forget about it?

**Comment by tomav** [comment]
Just added `enhancement` and `help wanted` if someone can get time to PR something.

**Comment by tomav** [comment]
I think I'm gonna close this issue and open another one to get a generator (script) to get files for opendkim.
We do the same for accounts management in v2, so it makes sense.
`start-mailserver.sh` is just a start script, and I think that config generation should be out of it.

Let me know what you think about it.

**Comment by auguster** [comment]
That's a good idea, it makes perfect sense.
