### ISSUE TITLE
daily annoying cron-mail from postfix-summary

### ISSUE THREAD

**Issue by helmutundarnold** [tomav/docker-mailserver#1326]
Since update to the lates verson and setup the pfflapsum package I receive a cron mail with subject:
`Cron <root@mail> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )`

From my understanding this shouldn'd be the case. 

## Context

The impact is that we - our admins receiving mails extra without any value for us.

## Expected Behavior

This cron-mail should go to /dev/null

## Possible Fix

Add a ` 2>&1 1>/dev/null` at the end - or make it configurable.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amount of RAM available:
* Mailserver version used:
* Docker version used:
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):
* image used:  v6.1.0-189-g2ad6672

**Comment by erik-wramner** [comment]
I fully agree, I've also seen the e-mail and it is irritating (though not bad enough that I have fixed it).

The problem here is that the file that needs to be modified is part of the standard installation, it is not one of our scripts. We could patch it, but I wonder why it is necessary. I've never run into this before.

**Comment by erik-wramner** [comment]
#1329

**Comment by erik-wramner** [comment]
This should be fixed now, closing as it works for me. Re-open or submit another issue if you still have trouble with it in latest.

**Comment by helmutundarnold** [comment]
Hello Erik,
just want to say thank you - its solved - great.
