### ISSUE TITLE
mail.err and mail.warn are not rotated

### ISSUE THREAD

**Issue by gizocz** [tomav/docker-mailserver#1337]
Only mail.log is rotated. Add also mail.err and mail.warn to /etc/logrotate.d/maillog.

**Comment by erik-wramner** [comment]
Sounds like a good idea, though hopefully those files are much smaller and don't have the same need for log rotation.

**Comment by erik-wramner** [comment]
Actually both mail.err and mail.warn are rotated, but for some reason they are handled by `/etc/logrotate.d/rsyslog` and not `/etc/logrotate.d/maillog`. Most likely because they are not used as the basis for the pflogsumm report. It works on my hosts and as the logs tend to be quite small I can't see a need to rotate them more often than weekly, which is the current policy.

I think we can close this.
