### ISSUE TITLE
Wrong version embedded in images

### ISSUE THREAD

**Issue by erik-wramner** [tomav/docker-mailserver#1364]
The wrong tag is embedded in produced images with the `VCS_VERSION` variable. The problem is that the build uses `git describe` which only includes annotated tags. Apparently the tag created when a release is created through the Github user interface is not annotated.

We can either fix it by changing the `Makefile `to use `git describe --tags` or we can decide to always tag manually with annotations. Unless there are good reasons to avoid using `--tags` I would prefer not having manual routines that can fail.

@fbartels what do you think? Shall we change the command in the `Makefile`?

**Comment by fbartels** [comment]
Hi, yes I think its a good idea to adapt the scripts so that you don't need to change your flow. Apart from the [makefile](https://github.com/tomav/docker-mailserver/blob/f69d30f62a82d3e5d7323ed1d999efbd43741f6a/Makefile#L3) also the [hook file](https://github.com/tomav/docker-mailserver/blob/f69d30f62a82d3e5d7323ed1d999efbd43741f6a/hooks/build#L3) for the Docker Hub needs to be adjusted.

**Comment by erik-wramner** [comment]
#1365
