### ISSUE TITLE
Cannot use wildcard for subdomains in vhost file

### ISSUE THREAD

**Issue by Expa86** [tomav/docker-mailserver#1379]
I am trying to set-up multiple subdomains dynamically and collect incoming mail into one account.

I try to add to postfix-accounts.cf:
```
user@intra5.ru
user@.intra5.ru
```

And resulting vhost file shows only:
`intra5.ru`

How can I add wildcard domain to vhost file?

**Comment by erik-wramner** [comment]
I don't think we support that. You could check the startup script and the change detector script to see if it is reasonably easy to add what you need. Based on a quick search it probably won't be enough to get that line into the file, it seems you need to add regular expressions as well.

**Comment by Expa86** [comment]
Thanks, I'll try to check the scripts. 
I'm using one regexp, that covers all created accounts (tested). I just don't want to create account every time, as it also restarts postfix, wildcard would be much better in this case.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
