### ISSUE TITLE
[LDAP] Distribution list based on group members

### ISSUE THREAD

**Issue by Zegorax** [tomav/docker-mailserver#1386]
Would it be possible to make LDAP distribution lists based on group memberships ?

For example : 
Group DN : cn=INFO-ACCESS,ou=Groups,dc=foo,dc=bar
Group "mail" attribute : info@foo.bar
Group "member" attribute : uid=Bob,ou=Users,dc=foo,dc=bar uid=Alice,dc=Users,dc=foo,dc=bar

Alice and Bob both have a "mail" attribute with alice@foo.bar and bob@foo.bar

It would be nice to have a system like this, so we can send an email to info@foo.bar and it will distribute to every member of the corresponding LDAP group.

**Comment by erik-wramner** [comment]
I don't use LDAP, so I'll flag this hoping someone that does will answer.

**Comment by AndreasBomholtz** [comment]
You can look at this guide: https://kb.kopano.io/display/WIKI/Postfix

Here they have 2 ldap config files for groups. 

ldap-groups.cf - Gets the group members
ldap-groups-expand.cf - Converts member ID's to mail addresses

Hope this works for you.

**Comment by Zegorax** [comment]
Hi Andreas, I fixed my problem a long time ago but forgot to post my config. I will do it soon

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by MohammedNoureldin** [comment]
@Zegorax could you show your settings please? This is interesting to see.

**Comment by MohammedNoureldin** [comment]
OK, got it working. Pull Request created to explain it in the documentation: https://github.com/docker-mailserver/docker-mailserver/pull/2303
