### ISSUE TITLE
Force From address

### ISSUE THREAD

**Issue by Yajo** [tomav/docker-mailserver#1387]
## Context

Well, this is more a feature request. Actually a feature request from @rafaelbn, who doesn't want to open the issue himself for some weird reason... :stuck_out_tongue_winking_eye: 

I'm using SRS with envelope and header rewriting to avoid any problems with spam filters. However, I'd rather be able to force a From address instead, just like Github does:

![2020-01-31_08-24](https://user-images.githubusercontent.com/973709/73523594-22f08480-4403-11ea-9dcb-69c8a248e0a6.png)

This allows mail receivers to handle notifications more comfortably under some circumstances, for instance when doing mail filters. Also seems less scary to people who don't know what SRS is.

## Expected Behavior

There should be a documented and supported way to do this.

## Actual Behavior

No way, or I cannot see it.

## Possible Fix

An env variable like `FORCE_FROM` that, if supplied, inhibits SRS and instead rewrites the From field for all outgoing email.

@Tecnativa TT20505

**Comment by erik-wramner** [comment]
Actually I don't think Github are rewriting the from address. More likely they are sending e-mail on behalf of someone, so the real sender is the Github system. That means SPF policies and DKIM signatures and the like will just work; Github is sending a message from Github, no problems. The sender name is just informational and irrelevant, it can be anything. I don't see what we should do to accomplish your goal really - feel free to suggest something more concrete though.

Working configuration for Postfix without docker-mailserver is an excellent start.

**Comment by Yajo** [comment]
Something like this? https://serverfault.com/a/674984/125479

**Comment by erik-wramner** [comment]
As I understand the post you basically need to disable SRS (to avoid double rewrites), override a few options in `/etc/postfix/main.cf` and add two new configuration files. If that is true, add the two new configuration files to the `config` directory which is mounted into the container. Don't enable SRS. Edit `config/postfix-main.cf` and add the configuration you need, pointing to the two new files with the correct paths. Done.

I don't know how that will work out in practice, but it should match the example you provided and it requires no changes. Good luck!

**Comment by rafaelbn** [comment]
Thanks @erik-wramner , really great your help. I will try to explain use case. Next week Yajo will try and we will see what happens.

- We use and implement for customers Odoo ERP.
- Odoo ERP inside is a message system as you can send and receive emails, like, CRM, sale orders, invoices, task, tickets, ....
- So Odoo receives (POP) emails and send messages (SMTP)
- When a user of Odoo send a message in a task to a customer "From" should be the name of the user + email should be like github (notifications@mydomain.com). And "Reply-to" is the "POP" in Odoo (a catchall)
- When the customer reply, reply to Odoo and Odoo notify followers of the task, so followers receive an email from Odoo of the customer and "From" should be the name of the customer + email should be like github (notifications@mydomain.com) because obviously Odoo SMTP is not authorized to send emails from any domain.

:pray: Thanks!

**Comment by rafaelbn** [comment]
We are discussing this with Odoo in https://twitter.com/__yajo/status/1231856438970114048

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
