### ISSUE TITLE
No wiki page about how to configure amavis

### ISSUE THREAD

**Issue by mrniko** [tomav/docker-mailserver#1389]
There is no any information how to configure amavis service. I figured out the name of config and location only when I looked in `start-mailserver.sh` script: 

 https://github.com/tomav/docker-mailserver/blob/2a6d8ca6fadcdd2d7a0f89e9d2080e12caa7a29b/target/start-mailserver.sh#L1432

Please consider to add wiki page regarding this topic.

**Comment by erik-wramner** [comment]
That is true, the amavis service should be configured reasonably well out of the box but of course it would be nice with better documentation. Perhaps you can make a stab at it?

**Comment by aendeavor** [comment]
@mrniko did you do it?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
