### ISSUE TITLE
infinite email loop

### ISSUE THREAD

**Issue by stygmate** [tomav/docker-mailserver#1402]
Hi,

I have a mail alias from xxxx@mydomain.com to yyyy@anotherdomain.com
(yyyy@anotherdomain.com is the mailbox of one of my customers)
but the email box at yyyy@anotherdomain.com is configured with a autoresponder and send back a message to xxxx@mydomain.com.
It will result in a infinite message loop.
Is there any way to be protected from such case ?

Have a good day.

**Comment by hanscees** [comment]
This seems to be a general postfix question and perhaps better ask this somewhere else? 


Perhaps there is a clue in here:
https://unix.stackexchange.com/questions/174003/rewriting-from-header-when-forwarding-email-using-postfix 

Seems to me there should be no mail-loop since the auto-reply should go to the original reponder (but better test that assumption)

**Comment by erik-wramner** [comment]
I agree, this is a pure postfix question. I would try upstream or https://stackexchange.com. I'll leave the question open in case someone has an answer though!

**Comment by stygmate** [comment]
Hi, I've posted the question to: https://stackoverflow.com/questions/60337284/infinite-email-loop-with-alias-when-auto-responder-is-activated-on-destination-e

**Comment by erik-wramner** [comment]
StackOverflow is for programming questions, you might get better results at https://serverfault.com/questions (though they dislike cross-posting).

**Comment by stygmate** [comment]
@erik-wramner also posted on serverfault :) thx
