### ISSUE TITLE
method to restart postfix after manual ssl certificate changes

### ISSUE THREAD

**Issue by hanscees** [tomav/docker-mailserver#1403]
## Context

I am using letsencrypt certificates that some other central hosts refreshes.
So for docker-mailserver I use the manual varable.

On the docker server with docker-mailserver I check on this central host for new certs.
I have a script that gets these new certs and places the certificxates in the docker volume docker-mailserver uses.

But after refreshing these certs I want to tell the container to copy the certs and reload postfix. Of course I do not want to restart docker or the entire container.

Should I write my own script, or is there a better way?
A scipt would do in pseudocode:

- script runs inside container every hour or so
- has a checksum on /tmp/ssl/*
- if checksum no longer fits, copies certs
- postfix reload

**Comment by erik-wramner** [comment]
You'll probably want to restart dovecot as well. I would actually restart the container, but you can of course use supervisorctl to just restart the services. That should be faster. In that case I would personally use an external script that runs a `docker exec` command to do the job in order to keep the container simple - alternatively you can create your script in the image and let the built-in cron run it.

There has been a PR for integrating something like this in the change detection script, but personally I think it is cleaner to keep it separated. The change script is complex enough as it is.

You could try to make the script into a generic SSL change detection script that we could add into the official image as a new cron job. In that case it should handle manually refreshed certs as well as refreshed letsencrypt certs and it needs to be tested. It would be a nice addition as I know several people have asked for it, mostly for letsencrypt!

**Comment by hanscees** [comment]
I have worked out a script to renew certificates. 
It's here: https://github.com/hanscees/dockerscripts/blob/master/scripts/tomav-renew-certs

On my test docker it works fine. 

Use-case it this:

1. Get new letsencrypt certificates on some exrternal host
2. copy privkey.pem and fullchain.pem to the tomav config directory. 
3. place the script in the container, for instance in the config dir, name it check4newcert.sh and chmod +x it
4. From outside the container you can run the script: docker exec mail /tmp/docker-mailserver/check4newcert.sh

The script will echo if it has loaded the new certs. 
Script will check certs with openssl for sanity, but now if they are too old and so on.

**Comment by hanscees** [comment]
As far as I am concerned this can be closed

**Comment by hanscees** [comment]
this is now in the FAQ 
https://github.com/tomav/docker-mailserver/wiki/Configure-SSL
