### ISSUE TITLE
The `env-mailserver` file that is downloaded in the installation process uses old `REPORT` options

### ISSUE THREAD

**Issue by warwickchapman** [tomav/docker-mailserver#1408]
## Context

The `env-mailserver` file uses `REPORT_RECIPIENT`, `REPORT_SENDER` and `REPORT_INTERVAL` instead of `PFLOGSUMM_TRIGGER`, `PFLOGSUMM_SENDER` and `PFLOGSUMM_RECIPIENT`.

## Possible Fix

Update to the new options.

**Comment by casperklein** [comment]
I noticed the same yesterday. https://github.com/tomav/docker-mailserver/pull/1409 should fix it.

**Comment by erik-wramner** [comment]
The old options are still supported, but I agree that it is nicer to use the new ones in the template.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
