### ISSUE TITLE
Configure Fail2ban Ignored

### ISSUE THREAD

**Issue by w3hr** [tomav/docker-mailserver#1410]
When i put an fail2ban-jail.cf file with the following content:

```
[DEFAULT]

# "bantime" is the number of seconds that a host is banned.
#bantime  = 10800

# A host is banned if it has generated "maxretry" during the last "findtime"
# seconds.
#findtime  = 600

# "maxretry" is the number of failures before a host get banned.
maxretry = 10
```

it will get ignored, howto fix this?

In my env-mailserver file i put `ENABLE_FAIL2BAN=1` and the docker-compose file is also adjusted.

When i set `ENABLE_FAIL2BAN=0` if have no problems with that

**Comment by erik-wramner** [comment]
Long time no updates. Can this be closed? If not, please elaborate. What is working and what is not working? What do you expect? What happens without the fail2ban-jail.cf file and what are you trying to do with it? Fail2ban should be functional (when enabled) without additional configuration. Are you trying to change the max tries or what?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
