### ISSUE TITLE
Improve SPOOF Protection protecting FROM header

### ISSUE THREAD

**Issue by guyguy333** [tomav/docker-mailserver#1426]
SPOOF protection is not complete, we can still cheat "From" field.

## Context

We need to ensure From field in email is owned by connected user sending email.

## Expected Behavior

If FROM field is not owner by connected user sending email, email must be refused and not sent.

## Actual Behavior

You can still SPOOF even using SPOOF_PROTECTION. How ? Using From mail header.
SPOOF_PROTECTION enables `smtpd_sender_login_maps/smtpd_sender_restrictions`, which protects `MAIL FROM`. However, you can still spoof using FROM field in mail header. This is not currently protected in Docker MailServer

## Possible Fix

According to https://unix.stackexchange.com/a/567047, it can't be solved directly in Postfix. It can be solved using Milter. I didn't test. We're using LDAP and I don't know compatibility.

## Steps to Reproduce

1. Enables SPOOF_PROTECTION
2. Send an email with FROM Header (!= MAIL FROM sent to SMTP)
3. Receive email with spoofed address

## Your Environment

* Amount of RAM available: 8 Go
* Mailserver version used: v6.2.1
* Docker version used: 19.05.03
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by erik-wramner** [comment]
Thanks for the good detective work. Personally I would not like to fix this if it is not supported in upstream. For me the risk that authenticated users that are allowed to send e-mail can spoof their From headers is a lesser evil than the more complex and error-prone setup with a milter for this. We could of course make it optional so that it is turned on by a new option or by code in `user-patches.sh` (with a wiki that describes how).

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
