### ISSUE TITLE
Using ldap-alias.cf or /etc/aliases with LDAP to get aliases?

### ISSUE THREAD

**Issue by white-rabbit07** [tomav/docker-mailserver#1441]
Hi.
With my actual installation it's possible to login as a LDAP-User (Active Directory server connection works fine).  Every user has an email-address of this style:
login@domain.de
(I used Rainloop to login, send and receive emails -- everything looks good)

But there is still a problem with the aliases:
I already changed the ActiveDirectory-field "mail" to givenname.surname@domain.de 
But when I try to send an email from login@domain.de to givenname.surname@domain.de  it comes back immediately with the error: User doesn't exist!

So I guess it's a problem with the file ldap-aliases.cf or with /etc/aliases.
I use:
query_filter = (mail=%s)
result_attribute = mail
in ldap-aliases.cf. But nevertheless it doesn't work.

In /etc/aliases there's just one line for root - nothing more.
So my question ist: What's the correct setting that every user can login as
givenname.surname@domain.de and send/receive emails with this alias-name, too?
Any hints for that?
Thank you.

**Comment by aendeavor** [comment]
Sorry for a very late response. Sadly, I don't know the answer. But have you found one?

**Comment by white-rabbit07** [comment]
No I don't have a solution so far ... but it should be possible?!

**Comment by aendeavor** [comment]
It definitely should be. Have you had at look at #1468? There seems to be a problem with `%s`.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
