### ISSUE TITLE
/etc/postfix/dhparams.pem seems not to be initialized on fresh run

### ISSUE THREAD

**Issue by Paku-** [tomav/docker-mailserver#1455]
Error msg logged:

postfix/smtpd[1793]: warning: cannot load 1024-bit DH parameters from file /etc/postfix/dhparams.pem -- using compiled-in defaults

## Context

Logged by postfix.smtpd on first tests emails

## Expected Behavior
/etc/postfix/dhparams.pem file should be filled with data before postfix start.

## Actual Behavior
Empty file

## Possible Fix

Just initialize with:

 openssl dhparam -out /etc/postfix/dhparams.pem 1024

(Not sure but it seems to help me ...)

## Steps to Reproduce
1.Follow official install procedure 

## Your Environment
Archlinux VM on ESXi

**Comment by Dubbeldrank** [comment]
I had the same problem, postfix wouldn't even start, i removed and pulled the image again to be sure. When you manually start postfix from within the container it seems to be ok. But the DH group isn't sufficient anymore according to the mailtest on https://en.internet.nl DH-2048 is to be phased out, 3072 and 4096 should be enough. But even generating them with openssl doesn't seems to be sufficient, i tried the 4096 from the github below and that one is fine. The problem is that it's gone when the container goes down and up.

https://github.com/internetstandards/dhe_groups

**Comment by Paku-** [comment]
On the other hand postfix build used require 1024 length only ...

**Comment by Paku-** [comment]
Same for /etc/dovecot/dh.pem but comment asks for 4096 value.
