### ISSUE TITLE
Docker HEALTHCHECK

### ISSUE THREAD

**Issue by youtous** [tomav/docker-mailserver#1464]
Hello !

## Context

> The `HEALTHCHECK` instruction tells Docker how to test a container to check that it is still working. This can detect cases such as a web server that is stuck in an infinite loop and unable to handle new connections, even though the server process is still running.

From [Docker documentation](https://docs.docker.com/engine/reference/builder/).

It could be nice to detect when one of the process running in the container fail to start.

For instance, if the dovecot service is stuck in a restart loop, no detection is done until an error appears on a mail client.

## Expected Behavior

The image should provide a way to check every of the supervisor processes.

## Actual Behavior

Not monitored.

## Possible Fix

Using a combination of [startsecs](http://supervisord.org/configuration.html?highlight=startsecs) and `supervisorctl status` it should be not difficult to monitor all the processes.

## Steps to Reproduce

Launch dovecot with an `SSL_CERT` and an `SSL_KEY` path which does not exist, dovecot will stay in a restart loop.

**Comment by erik-wramner** [comment]
Sounds cool. Note that some people are using podman and ARM and many run in Kubernetes. Not sure if that makes a difference, but it is something to consider.

**Comment by Ether009** [comment]
Just wanting to add to this that for Kubernetes, a healthcheck against a container is very easy. Kubernetes probes are quite powerful, while docker's native system is quite limited. Docker's own is limited to running a command, that runs within the container. If as an example the network isn't working right so the container is live but not listening to network, then such a check would succeed, despite not being live at all. With Kubernetes, you can do the same of having a command run, but you can also define a HTTP request probe. This probe is done from outside the container by the kubelet so it will verify that the network itself works. And since you can specify this probe to be to any URI you want, you could even set it such that it tests the full network path from outside the network, although I don't suggest that since if say your Ingress is broken, you may not want to have all containers constantly restarting while you're trying to fix that.

Anyway, point is, that this is how many services does this when they're designed to run in k8s. They have a tiny webserver that when hit, checks health and responds. This is usually combined with a webserver for providing statistics as well. But, one can also implement health checks in a way that requires neither a script to run inside the container, or a webserver to run. K8s also has TCP probes. Here you simply set up what port to connect to, and if something responds, it's considered live. It doesn't really work for a project like this since you'd need multiple probes, one for each part, but then again, this project basically goes against one of the fundamental principles of containers in general, one container, one task (not a complaint, just saying why these probes would not work for this project).

**Comment by youtous** [comment]
k8s is great but not everyone is using it.

That's why basic docker HEALTHCHECK is preferred over a specific healtcheck for k8s. Moreover, probing services on specific ports etc is sometimes managed by a 3rd party such as Elastic stack.

Considering that, a first basic HEALTHCHECK (using supervisorctl + test ports) is a good starting point. If you are willing to design a k8s solution it would be great, you can add eventually submit a PR ;)

**Comment by erik-wramner** [comment]
If we get one health check working it should be possible to use it for both cases and also for fully manual supervision (i.e. external scripts). K8s is very flexible and can most likely handle any solution designed for docker.

**Comment by Ether009** [comment]
Well my point was just pointing to the different options. If it's done by script, it can be used by both docker and k8s, if it's done by web service, it can only be done by k8s but it becomes a much more reliable check.

And monitoring with Elastic Stack... That's a completely different thing than Docker and k8s health checks. Monitoring that way will just tell you if a service is up or down. But container health checks are about making sure a container is up or down, and auto restart if it's not. Remember that in both Docker and in k8s, you can have multiple containers running that provides the same service on the same port and have docker load balance in between them. Like say you can have a mysql cluster. Every single container except one could be dead, and monitoring externally like with ES, will still report that service as being online, ready and perfectly healthy... Even though it's clearly not.

As for submitting a k8s solution... As I said, the good k8s solution would be to break all the components down into separate containers, which is still possible using the same image. One could after all simply override the entrypoint and run this same image multiple times, once for each service. Though that would be a lot of work with having to override configs and stuff for since it's not designed for that. Without such a breakdown, the only good way to do it, is by using a script that works for both.

**Comment by youtous** [comment]
> the only good way to do it, is by using a script that works for both.
I agree. The script will check inner services (postfix,dovecot,etc.) ports + `supervisorctl status`.

**Comment by gawindx** [comment]
I propose a very simple approach while waiting to have better, and this already makes it possible to monitor the state of the container (but not the ports) on the principle that supervisord autorestart the faulty services.
I share it for those who are interested.
Here is what I did on my side:

Create a file "inet_http_server.conf" which we map with the file "/etc/supervisor/conf.d/inet_http_server.conf"
In the "docker-compose.yml",
`volumes:`
`  - ./inet_http_server.conf:/etc/supervisor/conf.d/inet_http_server.conf`

This file contains the following lines:
`[inet_http_server]`
`port = 9001`
`; username = username`
`; password = password`
This will launch the supervisord web server on port 9001 (without or with authentication if the username and password lines are uncommented)

Then, we add these lines to "docker-compose.yml":
`     healthcheck:`
`       test: ["CMD-SHELL", "curl -f http://localhost:9001 || exit 1"]`
`       interval: 10s`
`       timeout: 10s`
`       retries: 3`
`       start_period: 120s`

If you want to secure the web connection to supervisord, simply uncomment the username and password lines in "inet_hhtp_server.conf" and modify the "CMD-SHELL" as follows:
`"curl -f -u username:password http://localhost:9001 || exit 1"`

**Comment by youtous** [comment]
> on the principle that supervisord autorestart the faulty services.

Supervisord is restarting faulty services even if they keep failing. Does your solution handle this case?

I didn't have time to make a PR on this but I've thinking about setting a defined value for [startsec](http://supervisord.org/configuration.html?highlight=startsecs),  unfortunately it come with side effects...

**Comment by erik-wramner** [comment]
@gawindx unfortunately I agree with @youtous, the most common problem we have is not that the whole container hangs or dies but that a single service fails and is restarted... and restarted... and so on. I would like to find a way to make supervisor quit after a certain number of failed attempts within a given time. If it quits the container dies and that is easier to detect.

Apart from that, can't the docker health check run a script? Then we could simply use supervisorctl status and see that everything is up without having to expose a web server that has no other function (and could be a security issue)?

**Comment by gawindx** [comment]
By using the directives `startretries` and `startsecs` jointly, one must be able to set up a script which will be able to return an error if a service passes in the state 'FATAL' ( a simple `supervisorctl status | grep FATAL`)

For my part, my "server" being (very) aging and at the limit of resources, in general it is the containers which tend to crash.

**Comment by Ether009** [comment]
Both would be needed. Setting startsec does nothing for providing a healthcheck as such, but providing supervisord status as a web service like that would. It's just that if a service is constantly restarting, then if it fails every time before reaching startsec, it won't be listed as being in running state in the web UI. Providing such a web UI, would not however give any status of the various services as a healthcheck. Even if they were all dead, the healthcheck would still give a clean bill of health unless supervisord itself becomes broken. But it's better than nothing.

I'd do suggest some way to configure the port value there if going this route. Because despite the name, that value can be set to 0.0.0.0:9001 as well in order to bind to all interfaces, which is helpful in as an example Swarm and K8s environments.

As for getting supervisord to quit if a subprocess dies too many times, well, it could be scripted if you have a script that parses the status for if something has died to much and simply kills pid1 if it has, since supervisord should be pid1, that should effectively bring down the container, which then lets the container service handle that failure state. Better then IMO to simply have such a healthcheck script that gives a non zero exit if a service has died too often. That gives the user control over this restarting through the container service instead since those healthchecks treats any non zero as unhealthy.

**Comment by youtous** [comment]
> By using the directives startretries and startsecs jointly,

That's the idea!

The side effect is https://github.com/tomav/docker-mailserver/blob/f0defda2a19f69eed44297df0836f331c4a306c3/test/tests.bats#L9 needs to be refactored in order to get the tests pass.

I agree with @erik-wramner, I don't think the web server is something required here seen we can achieve it with `grep` and `nmap`.

**Comment by erik-wramner** [comment]
@youtous can't we simply use a fairly large value for startsecs to make the tests pass? For example if we allow 2 minutes or so?

**Comment by aendeavor** [comment]
@youtous what's the current status here?
