### ISSUE TITLE
Not wanted dovecot quota

### ISSUE THREAD

**Issue by guillaumedc** [tomav/docker-mailserver#1480]
Recently, I've got quota error, but I didn't setup Dovecot quotas.
I'm searching a way to get rid of this issue, preventing me to deliver mails correctly.

## Context

I've got error when I'm trying to send mails.
The sieve rules are set using rainloop, and symlinked to `domain.tld/user/ .dovecot.sieve`.

## Your Environment

* Amount of RAM available: **16GB**
* Mailserver version used: **latest** (this one at the moment : "Created": "2020-04-30T15:33:13.507129492Z")
* Docker version used: **Docker version 19.03.8-ce, build afacb8b7f0**
* Any relevant stack traces ("Full trace" preferred):
```Error: Failed to get quota resource STORAGE: quota-count: Couldn't get size of mailbox dovecot.sieve: stat(/var/mail/domain.tld/user/.dovecot.sieve/tmp) failed: Not a directory```

**Comment by youtous** [comment]
Hi,
This bug seems related to the way sieve folder.

**Comment by youtous** [comment]
Hi,
The bug seems related to the way non directory are handled by Dovecot. 
Same issue: https://github.com/Mailu/Mailu/issues/143#issuecomment-272269590

> `maildir_stat_dirs=no` (default): Assume that all the files beginning with a dot in the maildir are maildirs. **You shouldn't have any non-directory files beginning with a dot in the maildirs**, but if you do you may need to set this to "yes", in which case Dovecot needs to stat() each directory entry, **which degrades the performance. Some filesystems provide the directory/non-directory status for free without having to stat()**. In those filesystems this setting is ignored. 
https://wiki2.dovecot.org/MailLocation/Maildir

Could you try to add `maildir_stat_dirs=yes` in your `
config/dovecot.cf`?

I'll investigate this bug and add an option to disable dovecot-quota.

**Comment by youtous** [comment]
I've also added an option allowing you to disable dovecot quota (https://github.com/tomav/docker-mailserver/pull/1482).

Before using it, can you test setting `maildir_stat_dirs=yes` with dovecot quota enabled? 

This issue is not related to dovecot quota but the way dovecot stat is configured with sieve; disabling dovecot quota without setting `maildir_stat_dirs=yes` will not solve to the root of this bug.
