### ISSUE TITLE
Always uses Port 25 

### ISSUE THREAD

**Issue by dmuensterer** [tomav/docker-mailserver#1490]
I have set the docker-compose.yml to only use ports 143 and 587 but the logs show that docker-mailserver tries to send using the (intentionally blocked) port 25. 
## Expected Behavior

Send over port 587
## Actual Behavior

Sends over port 25

## Steps to Reproduce

1. Fresh Debian 9 installation
2. Usage of default config files (only removed ports 25 and 993 from docker-compose.yml )
3. Fresh docker container
4. Try to send email to any recipient

## Your Environment

* Amount of RAM available: 3.75GB
* Mailserver version used: 2.1
* Docker version used: 19.03.8
* Environment settings relevant to the config: -
* Any relevant stack traces ("Full trace" preferred): -

Log:
```
May  3 16:25:31 mail postfix/smtp[875]: connect to gmail-smtp-in.l.google.com[74.125.133.27]:25: Connection timed out
May  3 16:25:31 mail postfix/smtp[875]: connect to gmail-smtp-in.l.google.com[2a00:1450:400c:c07::1b]:25: Cannot assign requested address
May  3 16:25:31 mail postfix/smtp[875]: connect to alt1.gmail-smtp-in.l.google.com[2a00:1450:4010:c03::1b]:25: Cannot assign requested address

```

**Comment by youtous** [comment]
Server to server on port 587 only is not the usual case covered by this image.
You will need to define a custom postfix configuration. 

A starting point: https://serverfault.com/questions/911172/configuring-outgoing-mail-to-port-587-on-ubuntu-postfix.

**Comment by erik-wramner** [comment]
Port 25 is _the_ standard port for mail delivery to and from other servers, so unless you listen on that port yourself and send to that port you will not be able to communicate with all domains. You could of course use a dedicated relay host that uses another port for sending (as described by @youtous above), but even so most other servers will try to deliver mail to you on port 25.

In short think twice so that you are sure about what you are doing; then read up on how it is done with Postfix. The same procedure should work with this image. Check the config folder for where to put the configuration options.

**Comment by dmuensterer** [comment]
Thank you.
I indeed didn't know that MTA's always communicate using Port 25.
I found this article on message transfer agents very helpful.
https://en.wikipedia.org/wiki/Message_transfer_agent
