### ISSUE TITLE
custom setup of SSL using letsencrypt

### ISSUE THREAD

**Issue by greenpdx** [tomav/docker-mailserver#1496]
## Context

I have a email server that handles many domains, but only one SSL cert.  

SMTP SSL main.sfq
# TLS parameters
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key

Dovecot SSL 10-ssl.conf
ssl_cert = </etc/dovecot/ssl/dovecot.pem
ssl_key = </etc/dovecot/ssl/dovecot.key

letsencrypt
/etc/letsencrypt/live/FQDN/***

docker .env
SSL_TYPE=letsencrypt

I want SSL for all my domains

## Expected Behavior

docwcot and postfix both use letsencrypt

## Actual Behavior

it uses the hard coded ssl

## Possible Fix

there are two way to fix it, 
1> change main.cf and 10-ssl.conf to point to /etc/letsencrypt
2> soft link the keys and certs to /etc/letsencrypt

I can do this manually, but if I have to spin up a new docker the fix is gone.

## Steps to Reproduce

1. run the docker using docker compose
2.use certbot to install letsencrypt certs on host

## Your Environment

* Amount of RAM available:
* Mailserver version used:
* Docker version used:
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by erik-wramner** [comment]
I'm not using letsencrypt myself, but many others are and it is fairly well documented in the [wiki](https://github.com/tomav/docker-mailserver/wiki/Configure-SSL). Have you tried to follow one of the working setups?

One gotcha is that the TLS certificate is for the mail server host, not for the mail domains. It is quite possible and very common to have a single server, `mail.example.com`, that serves multiple domains, `domain1.com`, `domain2.com` and so on. Then all those domains have `mail.example.com` as their MX record in the DNS and you only need a single TLS certificate for mail.example.com to handle all domains.

Finally a really ugly workaround is to do whatever you are doing manually in the `config/user-patches.sh` script. It runs when the container starts, so that way your custom code will run automatically when the container is created. Check the wiki first though!

**Comment by greenpdx** [comment]
Thanks for the info, I want to look bigger than I am. Each has its shared ssl key. I get it from multi webpages from one server.  I guess my question is how do you import existing keys.
The config/user-patches.sh is the way I will go.
