### ISSUE TITLE
[QUESTION] How to setup a mailing list

### ISSUE THREAD

**Issue by stezani** [tomav/docker-mailserver#1518]
Hi all, thank you for this project. I've installed with success the docker container in my system but i have a question: how can i create a mailing list with existing postfix installation? 

Thank you, 

Stefano Zaniboni

**Comment by youtous** [comment]
Hi,
You will need to do some adjustments, you can integrate Sympa or Mailman in the image or as a independent service sharing conf files with DMS.

---
_Question issue template should be used for questions,_

**Comment by youtous** [comment]
Please see https://github.com/tomav/docker-mailserver/issues/370

**Comment by erik-wramner** [comment]
A very simple mailing list can be implemented with aliases. For a "real" list you need to use mailman or some other external tool. Good luck!

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
