### ISSUE TITLE
Every connection uses the docker IP - not able to use fail2ban

### ISSUE THREAD

**Issue by GreedyBytes** [tomav/docker-mailserver#1536]
Hello, 

I really appreciate your docker-mailserver. It's just simple to use and also so big in functionality. So thank you very much for the hard work!

Everything is running so far. I've just one problem. Every connection comes from the docker network (172.26.0.1 in my case). 

So if I configure fail2ban to block bruteforce attacks on my server, It will block all connections.

As described in the .env, I've configured NET_ADMIN (cap_add) in my docker-compose.yml. But this doesn't help. 

Is there a way to work the external IP address of the connections? 

Any help is appreciated. 

Thanks in advance.

**Comment by erik-wramner** [comment]
Well yes it is, but it depends on how you expose your ports. If you expose them to the external public IP with docker then you should see the correct remote addresses. If you have something in between you need to do something to make it work. Search the wiki and other issues, I think you should find references for how to fix it with HAProxy at least. Otherwise please describe your network configuration in detail.

**Comment by GreedyBytes** [comment]
Thank you for your reply. 

After testing around, I could fix the IP problem.

I configured docker in the past, to not open ports in iptables on it's own. For this I used the /etc/docker/daemon.json and set `"iptables": false`.

This was causing the issue, that just internal IP's was used. After removing it, everything works fine.

Maybe this could be useful for the FAQ section?
