### ISSUE TITLE
Possible to whitelist "to" addresses?

### ISSUE THREAD

**Issue by Fmstrat** [tomav/docker-mailserver#1558]
## Subject
* [ X ] I would like to configure a not documented mail server use case

## Description
Is it possible to whitelist "to" address for those servers that are constantly blocked by SpamCop? Basically, if the email comes to "thisplace@mydomain.com", whitelist it? (I use different emails for every service).

I believe this can be accomplished somehow with `smtpd_recipient_restrictions`/`check_recipient_access` but not sure of the best way to integrate that with this system other than overwriteing everything in `smtpd_recipient_restrictions`.

Thanks!

**Comment by erik-wramner** [comment]
Quite possible, but I don't know. I'll flag it help wanted. Hopefully somebody will know.

**Comment by aendeavor** [comment]
It seems like noone knows. Any news on your side @Fmstrat ?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
