### ISSUE TITLE
No way to circumvent quarantine without using Spam Assassin

### ISSUE THREAD

**Issue by guardiande** [tomav/docker-mailserver#1571]
## Context

I was sending some legit test emails from my office account to my private account which is hosted on docker-mailserver. For whatever reason the mail contains a duplicate mime version header which make Amavis uncomfortable. Amavis quarantines the mail.

I would like to override this behaviour and get such emails anyways. That's what the `SPAMASSASSIN_SPAM_TO_INBOX` environment variable was invented for. But if you have Spam Assassin disabled (`ENABLE_SPAMASSASSIN=0`) that option is not accounted for.

### *What* is affected by this bug?

Mail delivery. The biggest problem is that the receiver does not notice without looking through the logs.

### *When* does this occur?

Sending emails with duplicate headers like mime version.

## Actual Behavior

The email gets quarantined and is not noticed by the receiver.

## Expected behavior (i.e. solution)

Allow for overriding this behaviour without having to enable Spam Assassin.

## Your Environment

This is on 7.0.0

**Comment by guardiande** [comment]
Forgot to mention: As a workaround one could use the custom `amavis.cf` or `user-patches.cf` to change the Amavis configuration (what I did for now).

**Comment by aendeavor** [comment]
Thanks for reporting.

Due to missing capacities, you would need to do this yourself. Can you contribute this?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
