### ISSUE TITLE
amavis does not turn on

### ISSUE THREAD

**Issue by sigedav** [tomav/docker-mailserver#1578]
I just installed the server and everything seems to be coming but I cannot send or receive emails ... looking in the logs I see that amavis does not raise, apparently problems with a file:
```
Config file "/etc/amavis/conf.d/49-docker-mailserver" is writable, UID 112, EUID 112, EGID 114 114
Suicide () TROUBLE in pre_loop_hook: SECURITY PROBLEM, ABORTING at /usr/sbin/amavisd-new line 12938
```
I would like you to help me with this problem.

**Comment by erik-wramner** [comment]
That is odd. What version are you using?

**Comment by aendeavor** [comment]
@sigedav anything new? Please check the permissions of these files under `config ` and `target`.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
