### ISSUE TITLE
Migrating docker-mailserver to a new host

### ISSUE THREAD

**Issue by icyphox** [tomav/docker-mailserver#1583]
## Subject
* [x] I would like some feedback concerning a use case

## Description

So I have docker-mailserver setup on a VPS, working perfectly fine. I have 3 users on it. What's the best way to migrate the entire config, including everyone's mail to a new VPS host?

**Comment by cottonthread** [comment]
> ## Subject
> * [x]  I would like some feedback concerning a use case
> 
> ## Description
> So I have docker-mailserver setup on a VPS, working perfectly fine. I have 3 users on it. What's the best way to migrate the entire config, including everyone's mail to a new VPS host?

Hi, I recently did an emergency migration due to a problem I had with the server. Thank God I had a backup that saved my life. I think the important thing is that you have this parameter enabled: ONE_DIR=1, because supposedly this way what the program does is that it tries to consolidate all the essential folders to a single directory, and this is how I do the backups. I reveal here the most relevant settings:
**volumes:**
...
```
    - $HOME/mailserver/mail/:/var/mail/
    - $HOME/mailserver/mail-state/:/var/mail-state/
    - $HOME/mailserver/logs/:/var/log/mail/
    - $HOME/mailserver/config/:/tmp/docker-mailserver/
```
...
**environment:**
...
`    - "ONE_DIR=1"`
...
And to make the migration/security copy:
`sudo rsync -azh --exclude /mailserver/mail-state/spool-postfix/dev/random --exclude /mailserver/mail-state/spool-postfix/dev/urandom $HOME/mailserver rsync://username@newsite.ltd/destinationfolder/`

I hope it will serve as a reference, and of course if you have a better method, thanks for sharing!

**Comment by erik-wramner** [comment]
Indeed, this is covered in the [wiki](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#what-about-backups). Provided that you are using ONE_DIR everything should be found in two directories (one for messages and one for config). If you are NOT using ONE_DIR then things are a bit messier as the configuration is spread all over the place, but as you have very few users it should still be managable.

**Comment by icyphox** [comment]
Ah, gotcha. That did the trick! Thanks, both of you. :)
