### ISSUE TITLE
ACME support not working with specified version in documentation

### ISSUE THREAD

**Issue by dmuensterer** [tomav/docker-mailserver#1587]
The usage of the ACME protocoll by using Traefik V2 does not work as specified in the documentation.
In contrary to the specified tag "stable", the "latest" tag needs to be used.
Otherwise, the following error will be thrown:
` Cannot access '/etc/letsencrypt/live/mail.example.net/fullchain.pem' or '/etc/letsencrypt/live/example.net/fullchain.pem'`
Please adjust documentation accordingly and specify the minimum needed version to use this feature.
Thanks!

### *What* is affected by this bug?
Usage of Letsencrypt SSL certificates

### *When* does this occur?
Everytime, when using the docker "stable" tag.

## *How* do we replicate the issue?

1. Use sample config as in Use docker-compose.yml as in https://github.com/tomav/docker-mailserver/wiki/Configure-SSL#traefik

## Actual Behavior

Throws error ` Cannot access '/etc/letsencrypt/live/mail.example.net/fullchain.pem' or '/etc/letsencrypt/live/example.net/fullchain.pem'`.
## Expected behavior (i.e. solution)

Should correctly use certificates as provided in acme.json

**Comment by bobsburgers** [comment]
I am also experiencing this. However I was already using latest it says is 13 days old. Are you sure that is the only issue? I am also using latest for traefik which is v2.2 and using v2.json 

I verified the cert is in their for the full domain. mail.domain.com and works fine on normal browsing ports. 
and since i get the same error message that means that it is looking for letsencrypt as the docs say.  `Cannot access '/etc/letsencrypt/live/mail.example.net/fullchain.pem' or '/etc/letsencrypt/live/example.net/fullchain.pem'`

SSL_TYPE=letsencrypt

      - type: bind
        source: /mnt/traefik_certs/acme-v2.json
        target: /etc/letsencrypt/acme.json:ro

it is a mounted gluster directory if that matters. but in my testing it does not seem to make any difference.

I am using an env_file with no environment vars in docker compose.

**Comment by erik-wramner** [comment]
You are correct, that has not been merged into stable yet. We will fix that soon, but in the meantime latest is the way to go.

**Comment by aendeavor** [comment]
@erik-wramner as mentioned in #1605, this issue implicitly calls for an updated stable as well. What do we do about this?

**Comment by erik-wramner** [comment]
@aendeavor indeed, it is probably high time to release a new version and a new stable. I usually want master to be stable (meaning no new commits and no errors reported) for at least a week before I promote it to stable and version it. I can create a release this weekend if things look good at that point. Alternatively next week if master is having problems.

**Comment by aendeavor** [comment]
Done with #1620
