### ISSUE TITLE
Send Only Mail Server

### ISSUE THREAD

**Issue by wzrdtales** [tomav/docker-mailserver#1615]
This container can't be used as a send only mailserver yet. The problem is the forced generated vhost file, which will cause the mailserver to try to deliver for those domains locally, even so it should never even try to receive anything.

**Comment by aendeavor** [comment]
Thank you @wzrdtales for following the contributing guideline with opening an issue and a corresponding PR; we value contributions to this project. I will post this answer here as well as on the PR, so don't get confused.

I think this idea is worth merging, but there are some flaws which will need to be fixed up, by you if you want this in `master`. First of all, for this feature, we will need to see tests to verify that it works properly. Moreover, the documentation needs extension too. But you said:

> I do not have too much time at hand, so I am just leaving that here, there is probably some work to do to pull it in [...]

Hearing you don't have time, and neither have we for this feature request, there is little chance this is going to be merged soon. If you're willing to invest more time in this, we will happily review and merge these changes. Therefore, I will close the PR for now and mark it as frozen. When the time has come for you or anyone else to pick up and finish this work, please rebase from (then) current master and create a new PR. I will close this issue too. You will not need to re-open it in case you create a new PR, because I now know about it. **Feel free to re-open this issue if you changed your mind and want to finish this work sooner than later**.

PS: Have a look at `make shellcheck`. The build failed just because of the shellcheck-tests.

**Comment by wzrdtales** [comment]
That was the intention behind it, I hard forked and adjusted it for my purposes and my way of giving back to open source very often is just sharing what is working for me, but not necessarily finishing it to the needed quality degree (I would love to, but if I would have time at hand I would invest them in my own open source efforts first and others second, and even for those I lack time :/). Should I really find time somewhat soon I will have a look again, otherwise hopefully someone else who didn't dedicate all his time to other things will fine tune it :)
