### ISSUE TITLE
function _setup_spoof_protection adds unconditionally  reject_authenticated_sender_login_mismatch 

### ISSUE THREAD

**Issue by grharry** [tomav/docker-mailserver#1684]
inside script start-mailserver.sh 
line  
sed -i 's|smtpd_sender_restrictions =|smtpd_sender_restrictions = reject_authenticated_sender_login_mismatch,|' /etc/postfix/main.cf 
adds reject_authenticated_sender_login_mismatch  unconditionally when spoof protection is on. 

This grows the parameter smtpd_sender_restrictions with same  setting, ( parameter_string *  count of container restarts ) ! 
Regards, 
Harry!

**Comment by aendeavor** [comment]
Hey Harry, thanks for reporting a possible bug. What would have been even better was using the issue template for bugs :) 

> inside script start-mailserver.sh
> line
> sed -i 's|smtpd_sender_restrictions =|smtpd_sender_restrictions = reject_authenticated_sender_login_mismatch,|' /etc/postfix/main.cf

This script is over 2000 lines long. Could you be a bit more specific?

> adds reject_authenticated_sender_login_mismatch unconditionally when spoof protection is on.

Isn't this what is supposed to happen? Here, the template would have explained this case.

> This grows the parameter smtpd_sender_restrictions with same setting, ( parameter_string * count of container restarts ) !

I'm not sure I understand.

---

**Please** open another issue **using the template** so we can identify this bug properly and fix it in time.

**Comment by grharry** [comment]
you missed the point man!

**Comment by aendeavor** [comment]
Indeed, due to a poor description on your side. Your comment is not only not helpful, but _disrespectful_ to those dedicating their time to these issues.

I may have missed the point, but only an explanation will help resolve this problem. Now either explain it properly, or leave it be.

**Comment by grharry** [comment]
I wonder who is misbehaving and who is disrespectful plus a big mouth! I also spend my time debugging the projects bash shell script, in which it seems that you participate as "what ever"  even though I gave you enough information to locate it and think about it, first think you do is "blame the messenger"! 
Mr.! All you had to do is a search string operation within your environment inside the file. 
Did you ? 
I guess not! 
Instead you had enough time to be wise complaining about a script being to big for you "a developer ?"  while you forgot the fact that a non-developer found it and spotted it! 

Now I wonder why I spend my precious life moments answering to a youngster with an attitude lacking manners!

**Comment by aendeavor** [comment]
***This issue is now being locked due to violation of the community guidelines set by this project.***

---

You violated what this project is pledging to, especially with:

1. > it seems that you participate as "what ever"

It does **not** matter what I participate as.

2. >  even though I gave you enough information to locate it and think about it

Even on request _you did not_, reaction with

> you missed the point man!

instead of providing the line, clearly provoking this conflict instead of working towards resolving it.

3. > All you had to do is a search string operation within your environment inside the file.
Did you ? I guess not!

You're wrong, it's not that easily resolved. What's more: Even small issues can have big consequences. Therefore, changing a small thing in a script can have huge consequences. Altering a line in this script may have profound impact.

4. > a youngster with an attitude lacking manners!

It does not matter how old I am.

---

This is in contradiction with the standards set by our [Code of Conduct](https://github.com/tomav/docker-mailserver/blob/master/CODE_OF_CONDUCT.md). Especially the points:

- Demonstrating empathy and **kindness** toward other people
- Being **respectful of differing opinions**, viewpoints, and **experiences**
- Giving and gracefully accepting constructive feedback
- Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience

We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of **age**, [...], **level of experience**, (or) **education**, [...]. We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community.

---

As this is unacceptable, enforcement of a **warning** is hereby done. From our [Code of Conduct](https://github.com/tomav/docker-mailserver/blob/master/CODE_OF_CONDUCT.md): "This includes avoiding interactions in community spaces as well as external channels like social media. Violating these terms may lead to a temporary or permanent ban."

Therefore, refrain from interacting with the community via issues, PRs or any other channels.
