### ISSUE TITLE
sasl-auth log spam 

### ISSUE THREAD

**Issue by ToxicMushroom** [tomav/docker-mailserver#1719]
```
2020-12-14 10:36:15,855 INFO exited: saslauthd_pam (exit status 0; expected)
2020-12-14 10:36:16,859 INFO spawned: 'saslauthd_pam' with pid 2318
```
These lines get spammed in the console log (as seen by the incrementing pid and time)

### *What* is affected by this bug?
anything I wanna debug or look at

### *When* does this occur?
While starting and after starting

## *How* do we replicate the issue?

1. Wasn't a problem before (whatever stable was on October 6)
2. pull new image
3. restart
4. problem happens

## Actual Behavior
spam in logs :c

## Expected behavior (i.e. solution)
no spam in my logs :c

## Your Environment

* RAM Usage: 1.88GB/3.84GB
* Mailserver version used: 7.2.0
* Docker version used: 20.10.0
* config: https://hasteb.in/eyusajox.ini
* trace: https://hasteb.in/ezalikef.bash

**Comment by aendeavor** [comment]
Alright. As far as I can see, you have `DMS_DEBUG=1`, so this is why you're seeing these info messages. My first response too was that these message are a kind of spam, but on second sight, I'd argue that maybe some `SASL`-related configurations are wrong on your side. I'd just like to make sure this is not the case. Since you have `ENABLE_SASLAUTHD=1` and no other configuration, you're using PAM (as seen in the configuration:

``` BASH
# empty => pam
# `ldap` => authenticate against ldap server
# `shadow` => authenticate against local user db
# `mysql` => authenticate against mysql db
# `rimap` => authenticate against imap server
# NOTE: can be a list of mechanisms like pam ldap shadow
SASLAUTHD_MECHANISMS=
```

). Is this intended? To me, it seems like something is preventing `saslauthd_pam` from starting correctly, which seems to be more of a configuration issue. I cannot remember "breaking" changes between `7.1.0` and `7.2.0`.

**Comment by casperklein** [comment]
fyi: I've also DMS_DEBUG=1 and do not see any `saslauthd_rimap` messages on startup.

**Comment by aendeavor** [comment]
> fyi: I've also DMS_DEBUG=1 and do not see any `saslauthd_rimap` messages on startup.

Thanks @casperklein for pointing this out.

And note here that `saslauthd_pam` is being used.

**Comment by ToxicMushroom** [comment]
okay I disabled sasl_auth and don't get spam, I'm unsure what sasl_auth does tho

**Comment by aendeavor** [comment]
When unsure, disabling a service is in my opinion the correct choice. I do not use it either, so I have it set to `0`. I guess this issue can be closed. Feel free to re-open when there's more.

---

SASL: <https://de.wikipedia.org/wiki/Simple_Authentication_and_Security_Layer> :D
