### ISSUE TITLE
Can I use multi processors?

### ISSUE THREAD

**Issue by astrocket** [tomav/docker-mailserver#1726]
## Subject

* [ ] I would like to configure a not documented mail server use case

## Description

Currently my mailserver only uses single core and it automatically gets suppressed.
Can I use multi processors with docker-mailserver?

Any option or documentation would be appreciated.

Thanks ahead.

**Comment by aendeavor** [comment]
Hey there @astrocket. I have to admit that I don't know what you'd like accomplish with this issue. Multicore scheduling and threading is the operating system's job to implement - processes are automatically run on different cores in modern operating systems. This project should automatically use multiple cores of there are ones, but not because _we_ made it - but because OS designers, Docker and the processes that are run were designed to do so.

_If_ you _really_ see only one core utilised by `Docker-Mailserver`, than it's your OS or you did something to make this happen. No matter what, this project, in a sense, is already multicore-ready, even though I would rather not call it that - since this is not one single piece of software (Programm) where explicit multi-threading is implemented. And since multiple processes are run here, multi-processing should automatically take place.

Few free to explain yourself further, but I'm sure the question you asked is not what could solve your problems.
