### ISSUE TITLE
Solve Fetchmail imap idle issue

### ISSUE THREAD

**Issue by brainkiller** [tomav/docker-mailserver#1728]
## Is your feature request related to a problem?

The known issue with fetchmail imap idle is already solved a few times.
You can also see the example on how to solve it + detailed problem description here: https://marek.dopiera.pl/2018/10/03/fetchmail-imap-idle-systemd-generators/

I suggest to adapt the solution a little bit to split the fetchmail conf in multiple entries per server and add those as new supervisor entries at startup.

**Comment by aendeavor** [comment]
@brainkiller Thank you for your tip. (I would have loved to see the feature request template being used.)

Nevertheless, I will keep this issue open since I think this is worthwhile. You'd need to provide a PR for this since capabilities are currently completely exhausted. Do you think that's possible?:)

**Comment by brainkiller** [comment]
If I find some time in the next couple of days I can probably make the changes and submit a pull request.

**Comment by aendeavor** [comment]
Nice. I'm sure that we can merge this after reviews are in.

**Comment by brainkiller** [comment]
FYI - I'm considering the pull request as complete unless if you request some additional enhancements.

**Comment by aendeavor** [comment]
Closed due to migration to [docker-mailserver/docker-mailserver](https://github.com/docker-mailserver/docker-mailserver). Please re-open over there :D
