### ISSUE TITLE
Webmin Integration

### ISSUE THREAD

**Issue by manthis** [tomav/docker-mailserver#178]
Hi,

Just had this idea while working on the rainloop docker image, it would be awesome to have a web admin interface to control postfix and dovecot. But I guess this would have to be directly integrated in docker-mailserver and not as an extra container. What do you think?

**Comment by tomav** [comment]
No, **we don't want to integrate such tools** in this image because we don't want to have a big and unmaintainable image. We want to **be focused on the core mail service** (smtp and associated filters + client protocoles like imap).

A webmail is a client for our point of view, because generally it users imap (like outlook, mail.app, thunderbird) to connect the server.
Webmin can help beginners but it won't help users to understand how a server works and how it should be configured using config files. Personnally, I started using linux with webmin and I did not learn a thing the first weeks.

We'll be happy to have such tools in our ecosystem, and to recommend them in our pages if they work well, so let us know how you figured it out.

**Comment by manthis** [comment]
Alright, no problem. It was just for a ease of use. But I doubt I can integrate it in a separate container.

**Comment by tomav** [comment]
Even using volumes ?

**Comment by manthis** [comment]
Maybe, but it will make things a lot more complicated. And I don't think I can do it if I don't create volumes on your docker-mailserver image.

**Comment by matze19999** [comment]
I created an dockerfile with rainloop, check it out :)

**Comment by erik-wramner** [comment]
@matze19999 that would be easier with a link. I assume that your container administers docker-mailserver?

**Comment by matze19999** [comment]
https://github.com/matze19999/Postfix_RainLoopOnDocker

Yeah :)

**Comment by erik-wramner** [comment]
Right, it doesn't administer docker-mailserver from the outside, but builds an adapted image with rainloop included. I have not problem with that of course, though I agree with Tom about not having it in this project. However, make sure you test it properly as it may conflict with how things is done. I assume that rainloop writes to the native Postfix configuration files and docker-mailserver also updates them from time to time. You may end up losing configuration when one tool overwrites the changes done by the other tool.

**Comment by matze19999** [comment]
I've tested it and it doesn't touch the postfix configuration or causes any issues 👌🏽

**Comment by erik-wramner** [comment]
Perhaps I missed your point. If it is just a webmail client, why don't you simply run it beside docker-mailserver as another container in the same compose file? That is much cleaner and you don't have to rebuild the image. In fact you should be able to use the official rainloop image (if there is one, couldn't find it) in that way without having to build anything.

If it is a web-based admin tool then it has to modify the configuration or there is no point with it. If it does modify the configuration it may run into conflicts.
