### ISSUE TITLE
554 5.7.1  : Relay access denied

### ISSUE THREAD

**Issue by zx2015** [tomav/docker-mailserver#19]
554 5.7.1 xxxxx@163.com: Relay access denied
And mail is not send out yet.

I checked internet, the possible cause might be auth for SMTP is missing. Recv side server might reject such mail without auth to prevent spam mail. And it seems smtp is not require auth.

But it look strange that my iphone works fine and can send email to outside mailbox.

My personal mail address gnesis@163.com.

**Comment by zx2015** [comment]
I found the problem is still in client configuration. If choose to have SMTP login in client, the problem will not existing.

Is it possible to change default configuration to force login for smtp before sending mail?

**Comment by tomav** [comment]
Yes, **SMTP Auth is a feature enabled by default** in this image, for security purpose as you can image.

And Yes again, you can disable it in postfix configurations files (`main.cf` and `master.cf`)
You should find how to do that searching on Google or [Stackoverflow](http://unix.stackexchange.com/questions/145499/postfix-disable-authentication-through-port-25).
I won't re-document Postfix again :-)

Since it's a Postfix related question, I close this issue.

Thank you.
