### ISSUE TITLE
plug Postfix with PostgreSQL

### ISSUE THREAD

**Issue by ppKrauss** [tomav/docker-mailserver#202]
I need  PostgreSQL 9.5 at UBUNTU 16 LTS + *Docker*...  So,  [plug Postfix with PostgreSQL](http://www.postfix.org/pgsql_table.5.html): it is possible with docker-mailserver?

**Comment by tomav** [comment]
Hi @ppKrauss, it's possible because I think that [Dovecot supports postgresql](http://wiki2.dovecot.org/HowTo/DovecotPostgresql).

You can do it on your own overriding config files but this won't be merged in the current master, the purpose of this image (when you pull it), it to be managed using configurations files.

That said, let us know how you figured it out, a Wiki page could be a good place for that and will probably help some other users.
