### ISSUE TITLE
How to make pop3 enabled?

### ISSUE THREAD

**Issue by septianw** [tomav/docker-mailserver#32]
imap and smtp was perfect with webmail interface. With pop3 enabled, it will match perfectly with mail client. How to make it enabled?

**Comment by tomav** [comment]
Hi @septianw, this image does not contain a `pop` server.
`pop` has been widely used, but today `imap` is the standard because it works better for multi-device synchronization. ([some](http://wpu.me/pop-vs-imap/) [sources](http://support.mightymerchant.com/pop-vs.-imap-which-should-you-choose))

This image won't include all use case because we want to to be easy to use and maintain, so that's why I decided not to include `pop3` server nor a webmail when I started to work on it.

But, for you personal use, the `pop3` server can be added to the list of needed packages in the `Dockerfile` and started with `start-mailserver.sh`.
The webmail *must* be another image. There are a lot of softwares available can that may exist in docker file format.

Hope this helps.
