### ISSUE TITLE
How to install signed SSL certs

### ISSUE THREAD

**Issue by kopax** [tomav/docker-mailserver#33]
I want to install my signed gandi certificate.

In `start-mailserver.sh` you have `if [ -e "/tmp/postfix/ssl/$(hostname)-cert.pem" ]`, the file doesn't exist but another file is present and not used by the script : __mail.domain.com-req__

 - Should I rename the file ?

I have tried by renaming it and it didn't worked : 

	CONNECTED(00000003)
	140445282178704:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:184:
	---
	no peer certificate available
	---
	No client certificate CA names sent
	---
	SSL handshake has read 0 bytes and written 295 bytes
	---
	New, (NONE), Cipher is (NONE)
	Secure Renegotiation IS NOT supported
	Compression: NONE
	Expansion: NONE
	---

Looking at the script : 

	  # Postfix configuration
	  sed -i -r 's/smtpd_tls_cert_file=\/etc\/ssl\/certs\/ssl-cert-snakeoil.pem/smtpd_tls_cert_file=\/etc\/postfix\/ssl\/'$(hostname)'-cert.pem/g' /etc/postfix/main.cf
	  sed -i -r 's/smtpd_tls_key_file=\/etc\/ssl\/private\/ssl-cert-snakeoil.key/smtpd_tls_key_file=\/etc\/postfix\/ssl\/'$(hostname)'-key.pem/g' /etc/postfix/main.cf
	  sed -i -r 's/#smtpd_tls_CAfile=/smtpd_tls_CAfile=\/etc\/postfix\/ssl\/cacert.pem/g' /etc/postfix/main.cf
	  sed -i -r 's/#smtp_tls_CAfile=/smtp_tls_CAfile=\/etc\/postfix\/ssl\/cacert.pem/g' /etc/postfix/main.cf
	  ln -s /etc/postfix/ssl/cacert.pem /etc/ssl/certs/cacert-$(hostname).pem

	  # Courier configuration
	  sed -i -r 's/TLS_CERTFILE=\/etc\/courier\/imapd.pem/TLS_CERTFILE=\/etc\/postfix\/ssl\/'$(hostname)'-combined.pem/g' /etc/courier/imapd-ssl

Because the provided sample is not working, I am trying to guess how it should work using this [explanation](http://wiki.queret.net/docs/ssl/certificats_gandi)

The servers only needs these 4 files :
 
1. mail.domain.com-cert.pem
1. mail.domain.com-key.pem
1. cacert.pem
1. mail.domain.com-combined.pem

I have buy my certs on Gandi, I was able to prepare this : 

1. mail.domain.com-cert.pem > certificat -> provided by gandi and contain 1 key
1. mail.domain.com-key.pem > generated key -> provided when generating the csr, contain 1 key
1. cacert.pem > GandiStandardSSLCA2.pem > provided by gandi, contain 2 keys
1. mail.domain.com-combiner.pem > concatened certificate > made by me, contain 4 keys __(mine x 1 + gandi x 2 + comodo x 1)__

Everything seems ok to me, I have tried, still not working.

Does anyone did tried to add their own signed certs ?

**Comment by tomav** [comment]
Hi @kopax, I quickly added the feature for self generated certs which simplifies the process if you don't have certificates. I'm pretty sure that in your case, you should mount a volume with your certs and apply a specific postfix configuration.

If you find a way to make it work, I'll be happy to merge your PR.
I'm not a SSL expert (only use self singed certs) but will probably have a deeper look in a few weeks.

**Comment by tomav** [comment]
I'd also like to make this image easy to use with https://letsencrypt.org/

**Comment by kopax** [comment]
Unfortunatly I have tried for a few hours and let it go. Can you leave this post open ?

**Comment by tomav** [comment]
Yep, we have to have a clear answer to SSL.

**Comment by tomav** [comment]
LetsEncrypt will go public beta on Dec 3.
https://letsencrypt.org/2015/11/12/public-beta-timing.html

**Comment by nathema** [comment]
Seem to have similar issues as @kopax .

I'm using valid signed certificates that I used with postfix on my previous server installation.

I prepared local storage:

    ayase ssl # pwd
    /srv/docker/mail/postfix/ssl
    ayase ssl # ls
    ca.pem  mail.mysuperdomain.tld-cert.pem  mail.mysuperdomain.tld-combiner.pem  mail.mysuperdomain.tld-key.pem sub.class1.server.ca.pem

And ran the container with `docker run --restart=always -d --name mail -v "/srv/docker/mail/mail":/var/mail -v "/srv/docker/mail/postfix":/tmp/postfix -v "/srv/docker/mail/spamassassin":/tmp/spamassassin -v /srv/docker/mail/postfix/ssl:/ssl -p "25:25" -p "143:143" -p "587:587" -p "993:993" -h mail.mysuperdomain.tld -t tvial/docker-mailserver`.

When I test the certificate from outside the container with `openssl s_client -starttls smtp -connect mysuperdomain.tld:25` the output shows an self-signed certificate.

**Comment by tomav** [comment]
@nathema do you provide your own postfix configurations?
Because as you can see [here](https://github.com/tomav/docker-mailserver/blob/master/start-mailserver.sh#L57) the script is waiting for 4 files named as expected (the `generate-ssl-certificate` tool name them as expected). It's not the case for your files so it won't work as expected.

I'm also thinking that's not the only problem. There's probably a bug or something to improve is the SSL part that I originally designed for self-signed certs only (because I currently don't own signed certs).

I'm open to any suggestion regarding SSL, I'm clearly not an expert on this part.
We'll also add integration test on the SSL part which is not covered yet.

**Comment by nathema** [comment]
@tomav Renaming the files precisely according to `start-mailserver.sh` fixed it. Checked with openssl. Thanx! 

After getting more familiar with docker, I might contribute to this project!

**Comment by kopax** [comment]
@nathema  what do you mean by "renaming the files precisely according to start-mailserver.sh" ?

I did it with the provided certs, not mine, it didn't work. 

How did you construct your own certs ?

**Comment by nathema** [comment]
@kopax As written in my previous post I prepared the files `mail.mysuperdomain.tld-combiner.pem` (typo!) and `ca.pem` (wrong name, wrong spot).

Contents of my `/srv/docker/mail/postfix/ssl`:

    mail.mysuperdomain.tld-combined.pem
    demoCA
    demoCA/cacert.pem
    mail.mysuperdomain.tld-cert.pem
    mail.mysuperdomain.tld-key.pem

**Comment by kopax** [comment]
@nathema great so you made it work.

can you post the key count of each pem files as I did ? It is still something I am not sure about.
As explained in my first post, I have : 

    mail.mysuperdomain.tld-combined.pem > concatened certificate > made by me, contain 4 keys (mine x 1 + gandi x 2 + comodo x 1)
    demoCA
    demoCA/cacert.pem > GandiStandardSSLCA2.pem > provided by gandi, contain 2 keys
    mail.mysuperdomain.tld-cert.pem > certificat -> provided by gandi and contain 1 key
    mail.mysuperdomain.tld-key.pem  > generated key -> provided when generating the csr, contain 1 key

**Comment by nathema** [comment]
@kopax ok.

Last year, I generated certificates for 2 of my domains using StartSSL (free certificates as long you don't have to revoke them =~ $40). Waiting for https://letsencrypt.org/ .

mail.mysuperdomain.tld-combined.pem => concatenation of mail.mysuperdomain.tld-cert.pem and cacert.pem.
demoCA/cacert.pem => StartSSL Root CA
mail.mysuperdomain.tld-cert.pem => 1 cert, received from StartSSL, after signing my generated CSR.
mail.mysuperdomain.tld-key.pem => 1 key, self-generated

**Comment by jokesterfr** [comment]
I'm also interested in using let's encrypt to manage my certificates, because my [rainloop installation](https://github.com/monder/docker-rainloop) does not handle self-signed certificates.

I think it would make more sense to create a separate Dockerfile/Docker project to certficiates, by providing an interface to monitor your service, keys validity and last update... Using volumes would suffice for *docker-mailserver*.

**Comment by tomav** [comment]
@jokesterfr, I think *letsencrypt* comes with its own docker project so it will be external the `docker-mailserver`. And you're right, it's better.
They currently only will provide help and tools for webserver. Since I'm not part of LE developer preview, I haven't try it myself and have to wait for december 3rd, when they'll open the public beta.

If someone has information, feel free to share.

We have to make LE easy to use / install with this container.

**Comment by jokesterfr** [comment]
I've just tried out their private beta, and it can generate credentials in `/etc/letsencrypt`:

```
/etc/letsencrypt/live/jokester.fr$ ls
cert.pem  chain.pem  fullchain.pem  privkey.pem
```

These are symlinks to:
```
cert.pem -> ../../archive/jokester.fr/cert1.pem
chain.pem -> ../../archive/jokester.fr/chain1.pem
fullchain.pem -> ../../archive/jokester.fr/fullchain1.pem
privkey.pem -> ../../archive/jokester.fr/privkey1.pem
```
So I guess the volume option will be `-v /srv/docker/mail/postfix/ssl:/etc/letsencrypt/live/<urdomain>/`

**Comment by tomav** [comment]
@kopax Let us know if these answers help you to resolve your problem. If yes, I let you close the issue.

@jokesterfr @nathema : I opened another issue for LE compliance.
https://github.com/tomav/docker-mailserver/issues/35

**Comment by nathema** [comment]
@kopax what bind volumes did you define for the container. Can you show us your directory structure for that volume. Is your hostname set correctly?
The script will write a line (`echo "Adding $(hostname) SSL certificate"`) to the log if it finds the files. Doesn't matter if they are valid certificates at that point in the script.

**Comment by tomav** [comment]
@nathema is right, if you don't see error at startup AND if you see `Adding $(hostname) SSL certificate`, they're loaded.
By the way, have you ever tried your files with another server?
The problem can also be related to the combined file. On my combined file, I count 3 keys in this file, not 4. But I use self-signed certs so there can be a difference. Here is a simplified example:

    $ cat mail.AZERTY.com-combined.pem
    -----BEGIN PRIVATE KEY-----
    AZERTY....
    -----END PRIVATE KEY-----
    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number: 
        Signature Algorithm: sha256WithRSAEncryption
            Issuer: C=FR, ST=Some-State, O=AZERTY, CN=AZERTY.com/emailAddress=ssl@AZERTY.com
            Validity
                Not Before: Nov  9 14:06:23 2015 GMT
                Not After : Nov  8 14:06:23 2016 GMT
            Subject: C=FR, ST=Some-State, O=AZERTY, CN=mail.AZERTY.com/emailAddress=ssl@AZERTY.com
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (2048 bit)
                    Modulus:
                        AZERTY...
                    Exponent: 65537 (0x10001)
            X509v3 extensions:
                X509v3 Basic Constraints:
                    CA:FALSE
                Netscape Comment:
                    OpenSSL Generated Certificate
                X509v3 Subject Key Identifier:
                    AZERTY...
                X509v3 Authority Key Identifier:
                    keyid:AZERTY...

        Signature Algorithm: sha256WithRSAEncryption
             AZERTY...
    -----BEGIN CERTIFICATE-----
    AZERTY...
    -----END CERTIFICATE-----


Anyone can confirm/infirm?

**Comment by nathema** [comment]
@tomav I have 3 base64 armored certificate-blocks in the combined file.

**Comment by kopax** [comment]
I still can't make it work.

Here are the step I did to get a signed cert : 

1. generate a csr + key
2. get signed crt from gani

So for every signed certs you have at least 3 files : 

- .csr (only for requiring the .csr)
- .key (obiously the key that goes with the cert)
- .csr (YOUR signed cert)

By agreeing this, we will also agree that : 

mail.domain.com-cert.pem __is__ the signed cert 
mail.domain.com-key.pem __is__ the key 

So we just need to agree on these points : 

- What is CA cert __precisly__ ?
- How do you create the __mail.domain.com-combined.pem


@nathema certificate are installed , I can see it from the log : 

    Adding mail.domain.com SSL certificate

**Comment by tomav** [comment]
@kopax here is how to build the combined file (extract from code):
    # Combine certificates for courier
    cat /ssl/$FQDN-key.pem /ssl/$FQDN-cert.pem >> /ssl/$FQDN-combined.pem

Regarding the open ssl ouput, when I see `Verify return code: 20 (unable to get local issuer certificate)` in your log, I clearly think that the problem is your `cacert.pem`

As said before, this feature has been created for self-signed certificates, so the container is waiting for `/tmp/postfix/ssl/demoCA/cacert.pem` that will be copied to `/etc/postfix/ssl` ([link to code](https://github.com/tomav/docker-mailserver/blob/master/start-mailserver.sh#L67))
This is a first check to do.

Next, could you confirm that these files exist in your running container?

    /etc/postfix/ssl/$(hostname)-cert.pem 
    /etc/postfix/ssl/$(hostname)-key.pem
    /etc/postfix/ssl/cacert.pem
    /etc/ssl/certs/cacert-$(hostname).pem (symlink to previous file)

**Comment by kopax** [comment]
cat /ssl/$FQDN-key.pem /ssl/$FQDN-cert.pem >> /ssl/$FQDN-combined.pem

Why are you concatenating the key and the cert together? these files shouldn't be together does it ?

All the files exist in the running container, this if obviously the first thing I have checked.

**Comment by tomav** [comment]
Have a look to [this link](http://www.mad-hacking.net/documentation/linux/applications/mail/using-ssl-tls-postfix-courier.xml) at section *"Configuring Courier POP3 and IMAP to use SSL/TLS"*

**Comment by kopax** [comment]
@tomav thanks a lot it did work.
I was really confused, in nginx and apache when you do the "chained" cert file, you just concat all the certs from your domain to the top certificate.

I have never seen a mixed key/cert, so It wasn't obvious at all to me. 
I let you decide if you should update the documentation and I close the post.

**Comment by tomav** [comment]
Hi guys, for those who wanna try LetsEncrypt support, have a look to https://github.com/tomav/docker-mailserver/pull/41

I'll merge soon.

**Comment by tomav** [comment]
Merged, you can now use Letsencrypt. Feedback welcome.

**Comment by virtualfunction** [comment]
Hi, I'm not sure how many other people are confused with installing SSL certs but this is what I found. I wanted to use an existing COMDO wildcard cert and I think there needs to be better docs for people who have brought certs (while Letsencrypt is pretty good, it can be a bit esoteric at times and throw up some odd errors when trying to generate certs and I might as well use existing certs), and there's no point self signing if you've already got proper certs.

For those using existing certs, I found it was best to make a folder where ever /etc/letsencrypt was mounted called live/<FQDN> where FQDN is the host used with the -h docker parameter.

Normally when you get certs from a CA you have a private key, this is generated when the CSR is generated. This needs to be located at live/<FQDN>/privkey.pem. Then there is the certificate for the domain self, and then there might be one or more certificates for the certificate authority. Normally all of these files need to be concatenated together so the domain cert is at the top, then the intermediate cert(s) from the certificate authority and the root-most certificate at the bottom. It's really important to do it in this order and I think a lot of people don't realise this if they aren't clued up with way certs work. This resulting file needs to be called live/<FQDN>/fullchain.pem - Finally there needs to be a file called live/<FQDN>/cert.pem. I've made the contents of this the same as live/<FQDN>/fullchain.pem although it looks like the this Docker image just expects it to be just the domain certificate. I've included the other intermediate CA certs because I think I had some issue with it not being able verify the domain fully. Either way it seems to work fine. I did find though I needed to copy this file rather than symlink it for some reason as the combined.pem file generated by the start up script wasn't generating correctly.

I think it makes sense to imitate the letencrypt layout given imitating the self signed structure if you have existing SSL certs is confusing due to the extra file generated for the dummy/demo self signed CA. I think you can get it working using either setup but letsencrypt seems better structured. I wonder if it might be better to make the self signed certs follow the letsencrypt structure so that it simplifies the `case $DMS_SS` block in the start up script and possibly gets rid of confusion as to where things go.

**Comment by tomav** [comment]
@virtualfunction I agree on the same structure for Letsencrypt and self-signed certs.
If you want to provide the PR, I'll be happy to merge it. I won't be able to work on it in the next weeks.
