### ISSUE TITLE
Update Password

### ISSUE THREAD

**Issue by ckiszka** [tomav/docker-mailserver#357]
Thank you for this docker! The wiki illustrates creating an account and password. Is there a command to update (change) a password? I'm nervous to attempt and lose access to mail without guidance. Any help is greatly appreciated. Thanks in advance. -- Chris

**Comment by Nesousx** [comment]
Hi,

In order to update your password, you can run the following command ::

`docker run --rm -e MAIL_PASS=Y0uR_P4$$w0rd! -ti tvial/docker-mailserver:latest /bin/sh -c 'echo "$(doveadm pw -s SHA512-CRYPT -p $MAIL_PASS)"'`

It will generate a string. Then, just replace the old password string with the new one inside **config/postfix-accounts.cf**.

This config file looks like this:
 

> user@domain.tld | password_string

NB : Please notice the pipe character between email and password.

**Comment by Brandl** [comment]
Maybe a takeaway from this is, that the setup.sh, should maybe support another command:

SUBCOMMANDS:

  email:

    ./setup.sh email add <email> <password>
    ./setup.sh email update <email> <password>
    ./setup.sh email del <email>
    ./setup.sh email list

Search for the EMail and replace the password.

**Comment by ckiszka** [comment]
Nesousx -- Thanks!

**Comment by tomav** [comment]
@ckiszka would you like to contribute to the project adding this feature on `setup.sh`?

**Comment by ckiszka** [comment]
@tomav -- I will give it a shot. This is new to me, it may take me a little longer than you guys ;)

**Comment by tomav** [comment]
No problem, we'll be happy to count you as a contributor!

**Comment by tomav** [comment]
Fixed by #413
