### ISSUE TITLE
Add SPF support

### ISSUE THREAD

**Issue by deacix** [tomav/docker-mailserver#451]
https://www.linode.com/docs/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-8

**Comment by tomav** [comment]
Hi @deacix, SPF is part of DNS configuration, its out the mail server scope it self event if closely related. What do you have in mind?

**Comment by tomav** [comment]
Perhaps we can leave a note in the Wiki as best practices.
Or perhaps add in `setup.sh` a SPF entry generator that can be copy/paste in the dns zone file.

**Comment by tyranron** [comment]
@tomav for outgoing mails yes, but for incoming mails it would be better to have a milter that checks their SPF headers. Currently [only DKIM and DMARC headers are checked](https://github.com/tomav/docker-mailserver/blob/2.1/target/postfix/main.cf#L71-L73).

In tutorial that @deacix has specified it's done via `postfix-policyd-spf-python` SPF policy agent. I have played with it earlier but without success (due to my Alpine-based images focus), but in Ubuntu-based image I think it's quite trivial to install via `apt-get`.

Alternatively, a [tiny and simple `smf-spf` milter](https://github.com/jcbf/smf-spf) may be used.

**Comment by tomav** [comment]
Oh yeah, I hadn't read the entire article. Let's add it. @deacix do you want to submit a PR?

**Comment by tomav** [comment]
Hi @deacix it would be great if you could contribute on that topic! Let us know.
Thank you.

**Comment by deacix** [comment]
Hi,

i am just on the time pressure. Can some else implement it? 

Sergej

**Comment by danielsreichenbach** [comment]
Pull request incoming within the hour. Currently testing.
