### ISSUE TITLE
missing: how to

### ISSUE THREAD

**Issue by AndreSchwarzer** [tomav/docker-mailserver#5]
1) Thanks for your Docker-"Image"
2) it would be nice to have a >how to< ... to a running docker instance 
2.1) add accounts
2.2) change passwords
2.3) add/remove aliases

BIG THANK YOU

**Comment by tomav** [comment]
Hi @AndreSchwarzer 

1) Thank You.
2) Done in the README.
2.1) Env variables.
2.2) Env variables.
2.3) Env variables.

I recommend using `docker-compose`, easier to understand, write and maintain.
I also recommend to use a data only container for you `/var/mail` folder.

Regards.

**Comment by AndreSchwarzer** [comment]
Thanks for your reply, but it is not exactly what I wanted to know.

I wanted to know how to change on the running docker instance a users password, add additional users/aliases ...

Thanks a lot.

**Comment by tomav** [comment]
@AndreSchwarzer, you have 2 options:
- change config on your running container: in this case I recommend you to have a look to Postfix / Courier-Imap documentation which will be more exhaustive than me. The problem is that when you will restart your container, your changes will be lost.
- set your config (user, pass, aliases) in your `docker-compose.yml`. This file can be versioned in a private repository. To apply a change, just restart the container. This what I recommend.

Hope this will answer your questions.

Regards.

**Comment by AndreSchwarzer** [comment]
Thanks a lot.
