### ISSUE TITLE
Aliases (config/postfix-virtual.cf) piping to script

### ISSUE THREAD

**Issue by markus-antoni** [tomav/docker-mailserver#505]
How to send mail content to a script? Simple tried adding the line to config/postfix-virtual.cf:
`support: "|/usr/share/redmine/rdm-mailhandler.rb --url https://redmine.example.com --key secret"`
But doesn't work. Any thoughts? In this case it's for redmine ticket system to receive mails.

**Comment by flole** [comment]
Have you tried to add the following settings to your `config/postfix-main.cf`?

```
allow_mail_to_commands = alias,forward,include
allow_mail_to_files = alias,forward,include
```

I found these settings here: http://ourlife01.blogspot.de/2012/04/how-to-execute-any-linux-script-using.html

**Comment by arneke** [comment]
@markus-antoni Did you find a solution ?

http://www.postfix.org/VIRTUAL_README.html#virtual_alias suggests it doesn't work with, I think the ourlife01 article echoes the documentation.

> There is one major limitation: virtual aliases and virtual mailboxes can't directly deliver to mailing list managers such as majordomo. The solution is to set up virtual aliases that direct virtual addresses to the local delivery agent

**Comment by markus-antoni** [comment]
For the moment I didn't find a solution. Simple checked for new mails over IMAP every minute.

**Comment by arneke** [comment]
Thanks for the reply, encouraged me to spend a fair bit of time on it.

I'm still digging around, but I'll share my notes since I have to write them down anyway, and there appears to be more than one way forward:
- .forward files do not appear to work, probably because the virtual accounts are not associated with shells.
- [Dovecot has extended Sieve](https://raw.githubusercontent.com/dovecot/pigeonhole/master/doc/rfc/spec-bosch-sieve-extprograms.txt) with the ability to run whitelisted programs, and this extensions appears to be included,  `/usr/lib/dovecot/modules/lib90_sieve_extprograms_plugin.so` , so need to investigate further.
- In the Postfix reference, they suggested forwarding from the virtual user to a local user, and then use /etc/aliases to run the command. I tried that (I'm a Docker noob, so I've just made the changes inside my image for now), by adding an alias file and modifying start-mailserver.sh

```
        if [ -f /tmp/docker-mailserver/local-aliases.cf ]; then
                # Copying aliases file
                notify 'inf' "Adding aliases and running postmap"
                cp -f /tmp/docker-mailserver/local-aliases.cf /etc/aliases
                postmap /etc/aliases
        fi
```

`postmap` is really the wrong command to use, but 
- newaliases gives an error message regarding missing texthash support
- postconf says `alias_maps = texthash:/etc/aliases`, and `postconf -m` lists texthash as available
- If I use postalias and actually send an email, the logs say `warning: /etc/aliases, line 1: record is in "key: value" format; is this an alias file?` .

So, strangely enough, *it* appears to want a regular `postmap` hashmap instead of the old Sendmail format.


where local-aliases.cf
```
test "|/usr/local/bin/test"
```

postfix-virtual.cf
```
test@somedomain.net test
```

For testing I've just used `/usr/local/bin/test` containing
```
#!/bin/bash
cat - > /tmp/test
```

I also had to add mydestination = $myhostname , which I think is okay as long as mail.somedomain.net is not a virtual destination.

Anyway, this still needs some QA, and I need to read up on Sieve, but appears tractable.

**Comment by arneke** [comment]
@tomav Are you interested in a pull request for either of these ?  
- allow the usage of /etc/aliases to pipe to script , afaict it requires mydestination to be set, but could maybe be set to "localhost".
- alternatively, enable the [sieve pipe plugin](http://wiki2.dovecot.org/Pigeonhole/Sieve/Plugins/Pipe) permanently in 90-sieve.conf , allow executables from conf/sieve-pipe (if the directory exists) ?

Not familiar with BATS, unsure how to really add tests for this except maybe check accepted delivery to local alias.

**Comment by tomav** [comment]
Hi @arneke, yes I'm interested if there's a need for that (and it seems to).
The proposed test should work. 
Regarding option, I let you choose with concerned people. Just think that I does not have to break anything for existing users.

Thank you.

**Comment by arneke** [comment]
I have a working implementation using Sieve (Using local aliases works too, I'm just not sure about the implications of adding mydestination).

https://github.com/arneke/docker-mailserver/tree/add-sieve-pipe-and-filter

Will need an update if #571 lands, since 90-sieve.conf probably has changed a bit.

Plan to submit a PR when I find time to figure out the tests, help welcome.

**Comment by tomav** [comment]
Available in master branch.
