### ISSUE TITLE
Cannot send or receive mail since latest update

### ISSUE THREAD

**Issue by Holt59** [tomav/docker-mailserver#507]
I just updated to the latest version, and I cannot send nor receive mail from the server !

I got this kind of error:

```
Feb  6 13:29:44 mail postfix/error[1425]: 3E94A301413: to=<xxxx>, relay=none, delay=0.31, delays=0.29/0.01/0/0.01, dsn=4.4.1, status=deferred (delivery temporarily suspended: connect to 127.0.0.1[127.0.0.1]:10024: Connection refused)
```

It looks like th is is related to AMAVIS (port 10024), so I checked the `/var/log/mail/mail.log` and saw:

```
Feb  6 13:26:52 mail amavis[1394]: starting. /usr/sbin/amavisd-new at mail.typename.fr amavisd-new-2.7.1 (20120429), Unicode aware
Feb  6 13:26:52 mail amavis[1401]: (!)Net::Server: 2017/02/06-13:26:52 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n  at line 70 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm
```

Any idea how to fix this?

**Comment by theomega** [comment]
I ran into the same error. I debugged this down an can explain what happened (see end for a solution)

1. postgrey was added in the new "version" of this docker container. This adds graylisting support and is per-se a nice feature.
2. Adding this feature also involved adding a new user `postgres` to the set of users inside the docker container
3. As this `postgrey` user is added before the `amavis` user (which existed even before), the user-ids (which are numerical) has changed (amavis was 107 before, with this new version, postgrey is 107 and amavis is 108)
4. The mail-state partition also contains the /var/run/amavis folder. This folder was originally (before the upgrade) owned by the amavis user.
5. After the upgrade, as the user ids changed, the /var/run/amavis folder is now incorrectly owned by postgres, because linux keeps tracks of owners by the ids and not by the names
6. Amavis fails to start because it can replace its socker at /var/run/amavis/amavisd.sock. This happens because amavis is no longer the owner of this file

Short-Term fix:
`docker exec mail chown amavis.amavis -Rv /var/lib/amavis/`

I think this is a huge issue, this could easily also happen with other users where the solution is not so easy. What are commons ways to mitigate this?

**Comment by tomav** [comment]
Hmm good catch! Hard to see this on small scale.
Perhaps we can add this to `start-mailserver.sh` like we did here: https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L903-L914

**Comment by evilstiefel** [comment]
Ran into the same issue, thanks @theomega for the quick solution.

Couldn't this be solved programmatically? E.g. using gosu and fixed user-ids for the services and file permissions during setup/building?

**Comment by tomav** [comment]
Just pushed a fix. Please give me feedback.

**Comment by tomav** [comment]
This fix does not seem to work. Checking.

**Comment by tomav** [comment]
Found.

**Comment by tomav** [comment]
If you don't need postgrey and want to avoir this bug, pull, the latest `2.1` image.
A new `2.2`image is plugged on `master` with postgrey and this current bug.

**Comment by tomav** [comment]
Just work on the fix tonight now I have my computer, and pushed a fix (this time should be good)

**Comment by tomav** [comment]
Done.
