### ISSUE TITLE
Separate services

### ISSUE THREAD

**Issue by strarsis** [tomav/docker-mailserver#539]
Wouldn't it improve maintainability and also robustness if the different mail services are separately run in containers with docker-compose instead using just one single monolithic container?

**Comment by tomav** [comment]
I've thought about that, but `start-mailserver.sh` does a lot of magic allowing to startup a full mail server in less than 10 minutes. There are a lot dependencies: if you activate amavis, amavis container should be started, and postfix conf should be adapted. 

That's why I voluntary chose 3 years ago to have this monolithic approach.
I'm open to changes, that's why I open sourced this image. But be careful, it's not that easy.

Feel free to share your plan if you have one.

**Comment by johansmitsnl** [comment]
@strarsis any suggestions on how to approach this?

**Comment by strarsis** [comment]
There is a similar mail server solution that separated out the services:
https://github.com/mailcow/mailcow-dockerized

**Comment by Exadra37** [comment]
Another good example of running a mail server with separated docker compose services can be found in [this docker compose file](https://github.com/Mailu/Mailu/blob/master/docs/compose/docker-compose.yml).

**Comment by erik-wramner** [comment]
There are other projects that work in other ways. While I agree with the basic idea of separate docker containers I don't see how this project could be changed that way without a major effort and breaking changes. It would be better to do that in a fork. Furthermore nothing has happened for years. I'll close this.
