### ISSUE TITLE
FeatureRequest: add dkim support

### ISSUE THREAD

**Issue by bilak** [tomav/docker-mailserver#55]
What about adding [dkim](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy) support?

**Comment by tomav** [comment]
:+1: 

I think @spacecowboy worked on it:
https://github.com/spacecowboy/docker-mailserver/commit/0704ff1bf64f5a48ec680705b495e1233ec2688a

**Comment by spacecowboy** [comment]
I never finished it though. Instead I implemented it and other things from scratch in https://github.com/spacecowboy/docker-post because I wanted to integrate with dovecot and use a database.

You can probably take most of the logic though. Some key points:

Setup of keys is done here: https://github.com/spacecowboy/docker-post/blob/master/postfix/run.sh#L3

Outgoing mail is signed with dkim via a milter: https://github.com/spacecowboy/docker-post/blob/master/postfix/master.cf#L42

Incoming mail signatures are verified by Amavis: https://github.com/spacecowboy/docker-post/blob/master/amavis/50-user#L23

**Comment by rubytastic** [comment]
Looks great; great repo only a bit to complex like the simplicity of this one.
Going to run this container soon and if time allows take a look at this also.

**Comment by tomav** [comment]
@bilak just PR this feature. Code is being reviewed.
https://github.com/tomav/docker-mailserver/pull/56

**Comment by tomav** [comment]
Merged.

**Comment by tomav** [comment]
@bilak does the server sign outgoing emails?

When I do `amavisd-new testkeys` I have:
`No DKIM private keys declared in a config file.`

Are you sure there's nothing to do in Amavis configuration?

Thank you.

**Comment by bilak** [comment]
Hi @tomav.
Yes it's definitely signing outgoing requests, but I'm testing this from java application in my laptop  and server with docker is another computer. Try to remove entries from `/etc/opendkim/TrustedHosts` reload the config and send mail.

**Comment by tomav** [comment]
Yes, you're right.

    BC0BB9F9: DKIM-Signature field added (s=mail, d=domain.com)

I was asking that because there are DKIM options in Amavis.
