### ISSUE TITLE
How do i connect to my mail?

### ISSUE THREAD

**Issue by SeunLanLege** [tomav/docker-mailserver#584]
So the docker container is running on my ec2 instance but how do i send and recieve mail?

i have an ngnix server running, and i've added the txt record to mail.strinix.com. i suppose i'll have to add a proxy to the container in ngnix. please how do i go about this?

your docs are very vague for people who don't know much about mail servers.

please any help will be appreciated.

**Comment by tomav** [comment]
Hi @SeunLanLege, I was trying to answer on Gitter but my connection is not reliable being in a train right now.
Some answers here:
- `docker-mailserver` is a **mail server** (allows to send and receive email from a technical standpoint). It's not **mail client** (end-user perspective). It's a SMTP/IMAP servers with additional features like spam/virus detection.
- It's not a webmail neither. So don't put it behind nginx. 
- If you can telnet from localhost but not from the outside world, your issue is probably your firewall configuration/rules
- If you don't know anything to a mailserver, I strongly encourage you to read a lot on the internet, especially about SMTP/IMAP protocols and softwares like Postfix and Dovecot that are included in this docker image. Security is very important on a mailserver, so don't do things that you don't understand.

Feel free to ask if you have more questions.

**Comment by SeunLanLege** [comment]
ok so how do i go about connecting to the mail server via thunder bird?

**Comment by SeunLanLege** [comment]
![logs](https://cloud.githubusercontent.com/assets/16494314/25538621/5caa0684-2c3b-11e7-8553-5784e7c5d3d0.png)

I've successfully connected to my mail server via thunderbird but i can send or recieve mails

here are the logs i get when i try to send mails.

**Comment by tomav** [comment]
Clamav is not running, are you using a micro/nano? You need at least 1GB RAM + Swap to run Clamav.

**Comment by SeunLanLege** [comment]
i'm running micro

**Comment by tomav** [comment]
Try with `ENABLE_CLAMAV=0` in your `docker-compose.yml` config and restart your container.
Virus detection will be disabled but this may run on micro.
If not, you will have to upgrade.

**Comment by SeunLanLege** [comment]
Thank you very much, i can finally send and recieve.

also thank you for this awesome project. and being here to resolve issues.

i just have one last problem.

mails i send to gmail always end up in spam folder.

how do i prevent this?

**Comment by tomav** [comment]
Search on Google, there are a lot of things to do, like configuring SPF, reverse DNS...
The remote SMTP server (Google) checks few things to be sure (or not) that the server who sends the email (yours) is allowed to send for this domain.
Mail content/format also plays a role.
