### ISSUE TITLE
function _setup_default_vars(): pastes all default env vars at every startup again to .bashrc

### ISSUE THREAD

**Issue by alinmear** [tomav/docker-mailserver#655]
With our current logic the `function _setup_default_vars()` sets the same key-value pair to the .bashrc again at every container startup until the container will be recreated.

We should add a check here to avoid this behaviour!

**Comment by johansmitsnl** [comment]
Why should this be avoid this?

**Comment by alinmear** [comment]
first, @johansmitsnl thanks for your reply.

I think this is more an aesthetic/best-practice problem then a functional one. In my use-case in production i have several Spamassin Rules-Files that are linked as a volume within the container. After changes to that i am rather restarting the container than recreating it (faster, less downtime).

**Comment by johansmitsnl** [comment]
Could you create a pull request for this?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
