### ISSUE TITLE
Allow unencrypted connection / no auth from localhost

### ISSUE THREAD

**Issue by strarsis** [tomav/docker-mailserver#670]
It would be very convenient if the mail server can be configured to always 
allow unencrypted connections - or even without any auth - from localhost clients.

**Comment by scottstensland** [comment]
It certainly can ... I send email using a login + password from localhost ... not sure what mod I've done ... if you post the output of   `  postconf -n  `   I will tell you how your settings differ from mine

**Comment by init-js** [comment]
For the mailserver to accept mail, without AUTH, from a client, you need to have  `permit_mynetworks` early on as a rule in the in `smtpd_recipient_restrictions`, `smtpd_sender_restrictions`, and `smtpd_recipient_restrictions` chains.

sending mail from localhost inside the container seems to work out of the box without having to modify anything.

if you're trying to send mail from a different container on the host, or from the host itself, then the sending IP should be included in one of the subnets listed in `mynetworks`. If you wanted to include any container from the docker bridge in the example above,  for instance, you'd have to have 172.19.0.2/16 (or whatever the network is defined as in docker) instead of 172.19.0.2/32.

**Comment by johansmitsnl** [comment]
Does this solve your problem?
https://github.com/tomav/docker-mailserver/blob/master/README.md#permit_docker

**Comment by strarsis** [comment]
Yes, this should work now for me.
