### ISSUE TITLE
Relayhost support

### ISSUE THREAD

**Issue by hubermi** [tomav/docker-mailserver#679]
Would it be possible to add a flag to add a relayhost like RELAYHOST = host that sets the proper configuration. 

I tried to get it running with the following manual configuration but to no avail:

In docker-compose.yml
SASL_PASSWD=host user:pass

in config/postfix-main.cf
```
relayhost = host
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = texthash:/etc/postfix/sasl_passwd
smtp_use_tls = yes
smtp_tls_security_level = encrypt
smtp_tls_note_starttls_offer = yes
smtp_tls_CAfile = /etc/letsencrypt/live/domain/fullchain.pem
```
But it does not seem to use smtp auth, as the log message says 
`Anonymous TLS connection established to host` and thus relay access is denied

Thanks!

**Comment by johansmitsnl** [comment]
@hubermi did it solve your issue using the SES variable?

**Comment by mcharris** [comment]
I was able to accomplish this by adding a postfix-main.cf to my config volume. In that config I added relay information. e.g.

mynetworks = 127.0.0.0/8 [::1]/128 [fe80::]/64 <YOUR NETWORK/IP HERE>

**Comment by hubermi** [comment]
@johansmitsnl I appreciate your support, unfortunately I didn't find time to give it a try yet, first some private issues popped up and then my server crashed. These issues are solved now and I will give it a try shortly and will let you know if it worked. Thx!

**Comment by jmarca** [comment]
I just got this working on my setup.  I *started* with your config, then compared that to my working config from my non-containerized postfix/dovecot.  I noticed one possible error in your setup...  You have

```
smtp_sasl_security_options = noanonymous
```

but I'm using 

```
smtp_sasl_tls_security_options = noanonymous 
```

Second, I did *not* add 

```
SASL_PASSWD=host user:pass
```

to docker-compose.yml.  Instead I linked my existing password file:

```
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      ...
      - /etc/postfix/sasl_passwd:/etc/postfix/sasl_passwd
```

My  `sasl_passwd` is a kitchen sink of all possibilities for communicating with my ISP because I have no clue, but it looks like:

```
# Contents of sasl_passwd
#
[smtp.myisp.com]:587            myispaccount@myisp.com:my_super_SECRET_isp_password
[smtp.myisp.com]:submission     myispaccount@myisp.com:my_super_SECRET_isp_password
... etc ...
```

(I'm pretty sure the 587 is the only one being used, but I had trouble way back when I set this up and so I have 5 or so lines that say the same thing with different ports, etc)

Anyway, I was *just* able to send email out from my laptop---through my server---via my ISP---to gmail, and then an email from my iPhone---through my server---via ISP--- to gmail.  So it seems to work (barring any hidden open relay issues)

I can post my full config files if you want.

**Comment by hubermi** [comment]
@johansmitsnl Finally I found time to test if the Amazon SES variables can be used, and it worked like a charm out of the box. Thanks!

@jmarca Thanks for your support, too, but I chose the solution johansmitsnl provided as it is easier.
