### ISSUE TITLE
Check availability mail-directory at startup

### ISSUE THREAD

**Issue by tbool** [tomav/docker-mailserver#717]
Hi,

I am running the mail-server on AWS using ECS on an instance with CoreOS operating system, with the mail-directory on a separate persistent EBS volume. CoreOS is configured to automatically reboot the instance when a new version of the operating system is downloaded.
During the last weeks it happened twice that the mail-server seemed to be working properly (could login into dovecot, read mails, send mails, etc.) only I did not receive any new mails. Checking the logs I found that upon receiving new mails postfix was not able to deliver them to the mailbox because it had no permission to. So these mails ended up in a "black hole". Each time this happened this was after a new version of CoreOS was installed and the instance was automatically rebooted. Apparently after a reboot and subsequent automatic restart of all docker containers the mail-server container gets restarted before the EBS volume is available.
Each time this problem occurred a simple manual restart of the mail-server container was sufficient to solve the issue, but each time 2 - 3 days worth of new mails got lost because it took me a few days to realise something was wrong.

I am no expert in bash scripting, but going through setup.sh I don't think there is a check in there if the mail-directory is available and if the system has permission to write to it.

Would it be possible to add such a check to setup.sh? Preferably in a loop that checks this every xx number of seconds and does not continue until the check is positive. This would ensure the restart of the mail-server is delayed until the directory is indeed available and writable, and in case that "never" happens there would at least be a clear indication to the user that something is wrong.

Best regards, Ton

**Comment by johansmitsnl** [comment]
I think the real question is why your ebs is not mounted yet?
I also run on aws but Ubuntu but almost every running service depends on the mounts in fstab.

Do you have log of the mailserver when it goes wrong?

**Comment by tbool** [comment]
Hi Johan, 

There is no fstab in CoreOS I am afraid. The EBS volume is mounted through the cloud-config file, along with some other basic services. 

But even so, there can be numerous reasons why the mail-directory would not be available at startup, but isn't it the responsibility of the docker container to check if all resources that it needs are indeed available at startup? 
It can also be other containers it depends on, or a database. 
In the docker images I develop myself I consider it good practice to check availability of all needed resources in the startup script.

Certainly in clusters where container orchestration systems like ECS (which I am using) or Kubernetes are being used it can always happen that nodes fail, are being restarted, and containers are restarted. In these environments I think docker containers must be robust, check availability of external resources and warn the user if something is wrong.

Unfortunately the log-files of the faulty containers disappeared when I “restarted” (restart is delete and recreate here...) them. I could probably recreate them by manually rebooting the AWS instance, but now is not a good time for that.


Best regards, Ton

**Comment by johansmitsnl** [comment]
A docker container in my perspective is the same as running a application/service on your machine. This container misuse the docker idea of one process per container but just for argument we take postfix as an example.
The service file that starts postfix has requirements, one of those requirements is a filesystem. During boot (in our case system.d) makes sure the fs is mounted before starting postfix because it is a dependency.
With docker it is the same, when you start a docker container dependencies should be met before starting. How can the program inside the docker know that they are missing? The container can only check for certain files, but those files are also missing when doing a clean start with no emails send.
Also you really depend on the type of program to detect failure. A normal postfix service would do the same if the directory is missing. Because it can start without any problems but when it will try to deliver email it rans into problems, this will not stop the postfix service but just log a warning. The same as inside the docker. I assume emails will be saved in the spool dir which is not on a permanent state dir (it also failed to mount). I understand what you mean but how to catch these exceptions for all services in the docker I would like to hear how this could be done.
I also don't know if you start the docker container that keeps checking if a directory is available will see the volume when the host mounts it. Does this mount get detected? I guess not because email will go in a blackhole. So a strategy would be to fail startup because dependencies where not met.

Can you share the code that you use to verify the availability of the resources for at least startup?

**Comment by tbool** [comment]
Naturally one cannot check all resources for availability at startup. Pure “internal” resources must be considered to be available assuming sufficient memory and CPU is allocated to the container. However to make the container stateless certain directories may be linked to directories on the host, so that when a container fails a replacement container with the same host directories linked will take it’s place without any additional intervention needed.

I think it is the possibility to link external host-directories that makes running a docker container different from running just any application/service on your machine. It makes the environment in which the application within the docker container runs less controlled. Therefore I think it is good practice to check if directories or files that have a high likelihood of being linked to directories or files on the host are available at startup. Certainly those directories and files that are crucial for operating the system and errors due to their unavailability would remain unnoticed.

I do not know postfix that well, but I suspect that in my case the file postfix-accounts.cf is not yet available at startup of the container. Postfix apparently is okay with that and starts up, but it doesn’t know about usernames and passwords, so it cannot deliver any new mails to the mailboxes. Hence the messages I see in the log that postfix has no permission to deliver the mails.
So I think at least a check on that one is required. The availability of the directory /var/mail is also very important, but if postfix already checks that herself, it is not necessary to repeat that.

Again, I am no expert in bash scripting, but something simple like:

	# Make sure postfix-accounts.cf is available
	echo "Checking if postfix-accounts.cf is available..."
	while ! [ -e /tmp/docker-mailserver/postfix-accounts.cf ]; do
	     echo “File postfix-accounts.cf not yet available.”  
  	     sleep 0.1 # wait for 1/10 of a second before checking again
	done

at the beginning of the startup script should do the trick. It will delay starting up the container until postfix-accounts.cf is available, and if that never happens it will just keep on looping. Since in that case the mail-server will not start it will be clear to the user that there is something wrong.
No doubt there will be more sophisticated solutions though… :-)

**Comment by johansmitsnl** [comment]
Keep in mind that for ldap enabled server this file does not need to be present.

I would prefer to exit the container with a error code. The container restart will take over but other error logging will be available instead of a non working container that is running waiting for the directory.

Could you create a PR for this?

**Comment by tbool** [comment]
I would certainly like to contribute where I can, but I am not a software developer, so I do not know what a PR is, or how to create one…

But always eager to learn, so if you could explain in a few words what a PR is and what I should do to create one, or point me to some documentation, I could certainly give it a try.

**Comment by johansmitsnl** [comment]
PR means pull request. 
You can read here more about it: https://help.github.com/articles/creating-a-pull-request-from-a-fork/
