### ISSUE TITLE
clamav restarting every second

### ISSUE THREAD

**Issue by MIvanchev** [tomav/docker-mailserver#721]
Suddenly starting the server started to cause an infinite number of the following messages:

```
2017-09-17 12:56:30,016 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-09-17 12:56:30,016 INFO exited: clamav (exit status 1; not expected)
2017-09-17 12:56:30,720 INFO spawned: 'clamav' with pid 1167

```

Restarting the host, deleting containers and volumes etc. doesn't change anything.

**Comment by johansmitsnl** [comment]
Is there enough memory available?

**Comment by MIvanchev** [comment]
More than enough, it worked without issues before the second-to-last update to latest. Since then it's always present.

**Comment by MIvanchev** [comment]
Hey, I've managed to isolate the cause somewhat. I am using a mount bind on /var/log OR /var/log/mail. As soon as I remove the bind, the server starts. With the bind however, clamav seems not to be able to create its directory.

**Comment by MIvanchev** [comment]
I think I just identified the cause. The /var/log/mail bind needs to be writable to everybody, because clamav tries to put clamav.log there. If that fails, the process seems to restart itself.

**Comment by johansmitsnl** [comment]
Is this issue related to the docker image our your setup?

**Comment by MIvanchev** [comment]
It's what I am trying to figure out, sir. Probably 50:50. When I bind <mydir>:/var/log/mail, <mydir> will, of course, not be accessible for the clamav user (created in the container). Therefore my only chance is to chmod a+w <mydir>. Or perhaps I am missing something?

**Comment by johansmitsnl** [comment]
My suggestion would be to fix this during startup. Your root in this script.
Could you add a PR for it?
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/target/start-mailserver.sh#L972-L974

**Comment by MIvanchev** [comment]
Sorry for the very late reply, my apologies! I fear I am not knowledgeable on the topic yet to do a PR, but I could look into it. I will need some time though.

**Comment by johansmitsnl** [comment]
Is this still an issue?

**Comment by MIvanchev** [comment]
I think so, but it's not a severe one, because there's a workaround. And it only affects certain setups. I would close it. In case someone encounters the issue and needs a fix:

you're probably encountering it, because you have bound the log directory of the server to preserve the logs, e.g. something like `/home/<someuser>/logs/mailserver:/var/log`. In this case create a directory called `mail` in `/home/<someuser>/logs/mailserver` with owner `root:root` and make it writable by everybody.

**Comment by n00dl3** [comment]
I had the same issue, but it was not the same cause. I erased my volumes with `mailstates` and I needed to run `freshclam` (which took so long) to update the database otherwise clamav was restarting forever with this error inside `var/log/mail/clamav.log`:
>Thu May  3 12:42:40 2018 -> +++ Started at Thu May  3 12:42:40 2018
Thu May  3 12:42:40 2018 -> Received 0 file descriptor(s) from systemd.
Thu May  3 12:42:40 2018 -> clamd daemon 0.99.4 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
Thu May  3 12:42:40 2018 -> Running as user clamav (UID 104, GID 107)
Thu May  3 12:42:40 2018 -> Log file size limited to 4294967295 bytes.
Thu May  3 12:42:40 2018 -> Reading databases from /var/lib/clamav
Thu May  3 12:42:40 2018 -> Not loading PUA signatures.
Thu May  3 12:42:40 2018 -> Bytecode: Security mode set to "TrustSigned".
Thu May  3 12:42:40 2018 -> ERROR: Can't open file or directory
Thu May  3 12:42:40 2018 -> Closing the main socket.
