### ISSUE TITLE
Relayhost

### ISSUE THREAD

**Issue by SilentFlyBy** [tomav/docker-mailserver#735]
I am sending my outgoing mails through a relay server. According to the readme I set the SASL_PASSWD variable to 
`relaydomain.com username:password`

But that alone didn't make postfix use the relay server. I also had to add 

`relayhost=relaydomain.com`
`smtp_sasl_password_maps=hash:/etc/postfix/sasl_passwd`
`smtp_sasl_auth_enable=yes`

in the postfix main.cf to make it work.

Would it be possible to add a RELAYHOST environment variable, which, if set, adds the stated lines to the config?

**Comment by dmcgrandle** [comment]
I also ran into this.  According to [this page](wiki https://github.com/tomav/docker-mailserver/wiki/Overwrite-Default-Postfix-Configuration) we can just create a postfix-main.cf file that gets added automagically to the config.  So I put the sasl_passwd.db file into the config directory and created a postfix-main.cf file also in the config directory with the following content.  

```
# set up remote smtp server sasl connections (for outgoing email to <relayhost>)
   smtp_sasl_auth_enable = yes
   smtp_tls_security_level = encrypt
   smtp_sasl_tls_security_options = noanonymous
   relayhost = [<relayhost>]
   smtp_sasl_password_maps = hash:/tmp/docker-mailserver/sasl_passwd

```
Adapt as needed.

**Comment by SilentFlyBy** [comment]
@dmcgrandle Your solution looks very solid to me, I adapted that. 
But still after starting the container, I have to connect into the container and run `postmap /etc/postfix/sasl_passwd` and reload postfix to make it work.
Is there any way to make this happen automatically?

**Comment by dmcgrandle** [comment]
@SilentFlyBy I actually created the sasl_passwd.db file outside of the container on another system - it is the hash database, not the text file with the username and password.  Then I put it into the ./config dir since that entire directory gets copied into the container to the directory /tmp/docker-mailserver/, that's why I reference it from there in the postfix-main.cf file instead of from /etc/postfix.  Also, I don't set any ENV variables for SASL, since this is all being done manually.  For me this works without needing to run postmap or reload postfix.

**Comment by johansmitsnl** [comment]
Using the SES variable should solve your issue.
Also see a duplicate issue that confirms it: 679
