### ISSUE TITLE
Fail2ban and local roundcube webmail (solved)

### ISSUE THREAD

**Issue by nknapp** [tomav/docker-mailserver#778]
I had this problem, I'd like to share my solution. Maybe this could be incorporated into the project, I'm not sure if anyone else needs this:

I have an compose-file that includes not only `docker-mailserver` but also `instrumentisto/roundcube`.
Both containers are in the same local subnet and it accesses the mail-services directly and not via the public ports on the docker-host.

The problem with `fail2ban` in this context is that the webmail-container will get banned completely when someone enters a wrong password at the web-frontend. I wanted `fail2ban` to completely ignore the webmail-host and the local subnet, but when you build the image, you don't know, what that subnet is...

My solution is pretty simple: Add a `ignorecommand` which checks if the route to the checked address goes through the gateway:

## `/etc/fail2ban/jail.d/ignore-command.conf`

```
[DEFAULT]
ignorecommand = /usr/local/bin/fail2ban-ignore.sh <ip>
```

## `/usr/local/bin/fail2ban-ignore.sh`

```bash
#!/usr/bin/env bash
set -e
# Only ignore if the route to the IP goes through the gateway
if [ -z "$( ip route get "$1" | grep via )" ] ; then
   logger "ignore $1"
   exit 0
else
   logger "do not ignore $1"
   exit 1
fi
```
I would submit a PR if you think this config is worth including into this project.

**Comment by curtiszimmerman** [comment]
Wow, great solution! You totally helped me out. I didn't even know fail2ban had this functionality, and it makes for some very interesting possibilities. Thanks for posting!

**Comment by chongma** [comment]
this should be included in the main project.  otherwise it would get wiped out when the container is rebuilt

**Comment by ianb445** [comment]
You can mount the /etc/fail2ban/jail.d folder in the docker-compose file and having created the ignore-command.conf file, create the fail2ban-ignore.sh in the ./docker-data/dms/config folder and edit the ignore-command.conf to to point to /tmp/docker-mailserver/fail2ban-ignore.sh (the folder is mounted ./docker-data/dms/config.

This however completely undoes any protection from fail2ban. In order to provide that protection you need to expose the roundcube logs and add a jail in the hosts version of fail2ban to read the log and block access. 

This is further complicated by having roundcube behind a nginx proxy, in this case, I ensure the proxy passed the X-Real-IP through to roundcube and am changing the fail2ban filter to block the x-real-ip.

I suppose this is simpler to just add a captcha to the roundcube login?
