### ISSUE TITLE
Setting up mail for IDN domain

### ISSUE THREAD

**Issue by andig** [tomav/docker-mailserver#794]
I'm trying to setup an IDN domain for proper IMAP handling across the toolchain and have various problems:

 - `domainname` has to be punycode
  - dovecot rejecting the login due to invalid characters (needs `auth_username_chars` or explicitly using punycode for user name in mail client)
  - postfix rejecting IDN recipient address (`NOQUEUE: reject: RCPT from unknown: 450 4.2.0 <foo@fötz.name>: Recipient address rejected: Delayed by postgrey`)
  - sending server received rejections (`SMTPUTF8 is required, but was not offered by host`)

I realize this is not docker specific but would appreciate any guide how to properly setup IDN support across the chain.

**Comment by crazystick** [comment]
When sending from Gmail, which appears to support IDN and even translates punycode back into the IDN, this is what I get:
```
postfix/smtpd[32165]: NOQUEUE: reject: RCPT from mail-xxxxxxx.google.com[12.34.56.78]: 554 5.7.1 <foo@bär.ee>: Relay access denied; from=<someone@gmail.com> to=<foo@bär.ee> proto=ESMTP helo=<mail-xxxxxxxx.google.com>
```

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
