### ISSUE TITLE
Critical security issue in Clamav !!!

### ISSUE THREAD

**Issue by kuche1991** [tomav/docker-mailserver#807]
This week seven critical vulnerabilitys in Clamav where found.
http://blog.clamav.net/2018/01/clamav-0993-has-been-released.html
The issues can lead to DoS-attacks and even to remote code-execution.
The currently installed clamav-version is still  **0.99.2**, which is vulnerable.
It needs to be updated to **0.99.3** as soon as possible.

**Comment by thiesschneider** [comment]
agreed!

**Comment by johansmitsnl** [comment]
It depends when Debian releases the update to the stable version.
Check https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888484 for the progress on this.

**Comment by mwlczk** [comment]
@johansmitsnl @thiesschneider we are safe already!
from the container: `clamav is already the newest version (0.99.2+dfsg-6+deb9u1).`
changelog for that version from here http://metadata.ftp-master.debian.org/changelogs/main/c/clamav/clamav_0.99.2+dfsg-6+deb9u1_changelog

clamav (0.99.2+dfsg-6+deb9u1) stretch; urgency=medium

  * Apply security patches from 0.99.3 (Closes: #888484):
    - fixes for the following CVE's: CVE-2017-6418, CVE-2017-6420,
      CVE-2017-12374, CVE-2017-12375, CVE-2017-12376, CVE-2017-12377,
      CVE-2017-12378, CVE-2017-12379, CVE-2017-12380.
   * Bump symbol version of cl_retflevel because CL_FLEVEL changed.

 -- Sebastian Andrzej Siewior <sebastian@breakpoint.cc>  Sat, 27 Jan 2018 00:33:28 +0100

bug may be closed.
