### ISSUE TITLE
Why configuration files in the universal tmp folder?

### ISSUE THREAD

**Issue by Exadra37** [tomav/docker-mailserver#832]
In my point of view storing the mail server configuration files in `/tmp/docker-mailserver` isn't wise from a security perspective.

A best solution would be to have them moved to a dedicated folder, outside `/tmp`, where it could only be accessed by the services needing them.

**Comment by 17Halbe** [comment]
Good point! 
It would be nice though to keep the config/ folder as it is. 
One solution would be mounting everything under root and delivering everything from there to the specific folders, but that would require monitoring those folders as well, since data might get altered via the container.
Or we would create a single mountpoint for every config file/folder.

Any other ideas?

**Comment by johansmitsnl** [comment]
@tomav could you add some thoughts about this why it was done in the past?

**Comment by Exadra37** [comment]
We don't need to change the structure of the `config` folder.

It will be enough to map a docker volume `/host/path/to/docker-mailserver:/docker-mailserver` and rename all current occurrences of `/tmp/docker-mailserver` to `/docker-mailserver` and adjust permissions if necessary.

**Comment by 17Halbe** [comment]
If we want to keep the files all in one place, we would have to change the ownership depending on the  file (or some folders)and limit read/write access to only the owner(probably group?). Which is definitly no problem, but that could also be done in the tmp folder. There wouldn't need to be a possible breaking change of moving the config folder somewhere else. 
Or am I missing something here?

**Comment by Exadra37** [comment]
No matter how we chmod it, using `tmp` folder for this is not a good security practice and in my opinion should be fixed.

**Comment by 17Halbe** [comment]
I agree, it leaves a wrong "gut feeling", but can you elaborate what kind of security holes/attack vectors persists if we would change the ownership and access-rights of a file to the respective owners only? 
So far I can't figure out one and my "gut feeling" right now isn't strong enough to justify such a major change, especially if there's no real security issue.

**Comment by johansmitsnl** [comment]
Could you provide a PR for the change to see what might break?

**Comment by Exadra37** [comment]
I can, but once I am not using this mail server or any other one for now I may not be the best person to fully test it, thus the current users will have to ensure it does not break anything ;)

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by georglauterbach** [comment]
The Helm charts are indeed not perfect; we have a dedicated repository in docker-mailserver organisation; can you please open an issue at <https://github.com/docker-mailserver/docker-mailserver-helm>. One more thing: you will probably need to provide the PR to fix this yourself since we do not have active maintainers for this repository IIRC.

I may be able to help since I am running DMS in K3s as well.

**Comment by allanger** [comment]
@georglauterbach But it's not an issue with the helm chart, because I'm using my own helm chart. I think that the problem is in this project. Or is there a way to use a custom path for configs, not the `/tmp` dir?

**Comment by georglauterbach** [comment]
I understand.

> Or is there a way to use a custom path for configs, not the `/tmp` dir?

No, there is currently none.

---

Why does mounting a volume to `/tmp/docker-mailserver` and then copying everything in there not work? Even when you mount a tmp-dir (empty) to `/tmp`, mounting another volume `/tmp/docker-mailserver/` works and is a non-issue. Moreover, this way you can back up the volume mounted to `/tmp/docker-mailserver/`.

**Comment by allanger** [comment]
I've tested it and it seems to work. It just doesn't feel nice to me to mount something to the `/tmp`, because it doesn't give me enough confidence that this volume won't be wiped by pod restart. I guess I need to have learn, how volumes mounted to `/tmp` act. Thanks

**Comment by georglauterbach** [comment]
Volumes mounted inside `/tmp/` do not behave differently from volumes mounted somewhere else, so you needn't worry :)

**Comment by allanger** [comment]
I was not really concerned about the volumes behaviour. 
But I'm just not 100% sure how the `/tmp` dir is cleaned up during restarts on linux. Does it also apply to containers or not. And if if does, when exactly it's happening and how it plays with mounting volumes there. But I guess it's a good thing to learn.

**Comment by casperklein** [comment]
> IIRC `/tmp/` is cleaned as it a tmpfs,

In debian `/tmp/` is not mounted as tmpfs. However, there is a startup script or similar, that cleans `/tmp`.
