### ISSUE TITLE
Postscreen is blocking sending with authorized SMTP

### ISSUE THREAD

**Issue by mzedeler** [tomav/docker-mailserver#870]
It seems that https://github.com/tomav/docker-mailserver/pull/799 is currently stopping me from sending outgoing mail, because my IP address is listed by spamhaus (ask my ISP why that is):

    Mar  2 19:25:28 mail postfix/postscreen[3222]: CONNECT from [X]:17308 to [Y]:25
    Mar  2 19:25:28 mail postfix/dnsblog[3227]: addr X listed by domain b.barracudacentral.org as 127.0.0.2
    Mar  2 19:25:28 mail postfix/dnsblog[3226]: addr X listed by domain zen.spamhaus.org as 127.0.0.4
    Mar  2 19:25:28 mail postfix/dnsblog[3228]: addr X listed by domain bl.mailspike.net as 127.0.0.11
    Mar  2 19:25:34 mail postfix/postscreen[3222]: DNSBL rank 6 for [X]:17308
    Mar  2 19:25:35 mail postfix/tlsproxy[3254]: CONNECT from [X]:17308
    Mar  2 19:25:35 mail postfix/tlsproxy[3254]: Anonymous TLS connection established from [X]:17308: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
    Mar  2 19:25:35 mail postfix/postscreen[3222]: NOQUEUE: reject: RCPT from [X]:17308: 550 5.7.1 Service unavailable; client [X] blocked using zen.spamhaus.org; from=<my@address.snip>, to=<my@address.snip>, proto=ESMTP, helo=<[SNIP]>

How do I disable postscreen or make it accept authorized senders?

**Comment by johansmitsnl** [comment]
See #838

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, open a PR based on the current master branch so we can review it.
