### ISSUE TITLE
Find alternative fail2ban setup for docker swarm mode

### ISSUE THREAD

**Issue by alexanderkjeldaas** [tomav/docker-mailserver#875]
In swarm mode, CAP_NET_ADMIN can't be set for iptables to work.

An alternative way to do this is to run fail2ban on the host and having a pre-cooked setup for the required rules.

Yet another alternative is (maybe?) to have a separate docker image that runs outside of swarm mode, with `--net=host` and with some sort of access to the logs of the swarm service.

Maybe there are other setups, but for swarm mode to work, fail2ban probably needs some special treatment.

**Comment by johansmitsnl** [comment]
The issue is much lower in the docker stack. See https://github.com/moby/moby/issues/25526 for the ongoing issue there.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, open a PR based on the current master branch so we can review it.
