### ISSUE TITLE
Debian update

### ISSUE THREAD

**Issue by mwlczk** [tomav/docker-mailserver#893]
Debian 9.4 released - https://www.debian.org/News/2018/20180310

Clamav 0.99.4
Opendmarc 1.3.2-2
Postfix 3.1.8

Those packages might need some attention

**Comment by scottstensland** [comment]
current is using debian 9.5



	root@mail / # lsb_release -a
	No LSB modules are available.
	Distributor ID:	Debian
	Description:	Debian GNU/Linux 9.5 (stretch)
	Release:	9.5
	Codename:	stretch

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, open a PR based on the current master branch so we can review it.
