### ISSUE TITLE
Push service - looking for feedback

### ISSUE THREAD

**Issue by 17Halbe** [tomav/docker-mailserver#928]
Hey there,
 
I would like to introduce an image I build, which is basically an addon to this image.
It's based on [z-push](http://z-push.org/) and is providing push functionality for this mailserver. 

So far I only tested it with my setup. And I would like to see others try it out as well, before I write a wiki entry about it. 
So if you would like to give push a try, get the image from docker [17halbe/z-push](https://hub.docker.com/r/17halbe/z-push/) and for any support ask here or even better at github [17Halbe/z-push ](https://github.com/17Halbe/z-push).

Questions? Comments? Suggestions?

**Comment by 17Halbe** [comment]
Just found a bug, don't use the TIMEZONE variable for now.. Sorry, but currently docker isn't building.

**Comment by cyrinux** [comment]
Could you please made IMAP_OPTIONS editable via ENV ? Thx !

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
