### ISSUE TITLE
"email del" does not remove data directory, even if it says so

### ISSUE THREAD

**Issue by callmemagnus** [tomav/docker-mailserver#949]
## Context
While investigating my failing test on my PR (https://github.com/tomav/docker-mailserver/pull/884), I discovered that one feature is not working as expected and its test fails to provide guard.

When running `./setup -c mail email del a.user@server.com`, there is an option to delete the data folder.

Sadly when that option is selected (-y or y at run time), it does not delete the directory.

## Expected Behavior

The user should be removed from the account file and if I wish the maildir folder should be deleted too.

## Actual Behavior

Mail folder is not deleted.

## Possible Fix

The script delmailuser is ran from setup.sh in a docker "run" command. This command only mount the configuration directory and not the persistence of the mail folder so obviously the "normal" server will not have its maildir (inside the container or on the host filesystem) deleted as it only tries to delete a folder in a docker run once container.

## Steps to Reproduce

1. launch the setup for tests "mail, mail-xx"
2. add a user through the script
3. delete a user through the script
4. check the existence of the folder on the main "mail" container

## The impact

The test that is supposedly validating this feature does not its job and fails to "see" the issues.

I will comment that test in my PR as it does not work as expected (when I finish)

**Comment by 17Halbe** [comment]
Yes, I just started redesigning the tests today and realized that useless test as well. (the `delmailuser` script works as expected, but the setup.sh script is running against the image, not the actual container.)
Workaround would be to call the `delmailuser` script from within the container. (`docker exec mail delmailuser ...`)
Will be fixed with my next PR! Thanks a lot for reporting!

**Comment by Rillke** [comment]
@17Halbe @callmemagnus any progress on this?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
