### ISSUE TITLE
Possibility to whitelist a sending IP/network to use this server as a relay

### ISSUE THREAD

**Issue by capi** [tomav/docker-mailserver#951]
I am currently trying to setup my home network to use my server as a mail relay. Unfortunately adding my home IP to `mynetworks` via `postfix-main.cf` does not work, since still all SPAM checks are still performed and my provider's IP range is listed as dialup and therefore is blacklisted by spamhouse.

## Context
I'd like to add hosts and/or networks as "trusted", so that they can use the server as mail relay and/or send to local recipients/aliases.

## Expected Behavior
Have a configuration option to add hosts/networks to `mynetworks` and add to the various whitelists of DKIM, spamassasin, etc.

## Actual Behavior
Overriding `mynetworks` from `postfix-main.cf` is messy, since it does not automatically add the container's IP address as well and also it does not add the hosts to the whitelists.

**Comment by capi** [comment]
Unfortunately I'm talking about an external host, outside the local LAN.
I'm currently thinking about maybe creating a user for the server and configure the remote `postfix` to use the mailserver via login on port 587.

**Comment by johansmitsnl** [comment]
From a security perspective unauthorized accounts are always better.
Accounts are free so creating a few for each service is the way to go.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
