### ISSUE TITLE
At Rest Mail Encryption

### ISSUE THREAD

**Issue by pfmsny** [tomav/docker-mailserver#958]
What would be the easiest way to do this? I tried changing the mail volume to the host file system and encrypting the directory with encfs, however, was faced with permissions errors from Dovecot. Is there a better way to do this? 

** Note ** I am aware of the limitations of at rest encryption

**Comment by capi** [comment]
I'd have gone for `encfs` as well. You'll most-likely need to run it as `root` and allow non-root users as well using `-o allow_other`.

**Comment by pfmsny** [comment]
Hi Capi, thanks for the response. Did you encrypt the entire container or just he email directory? Are you storing the mail outside of the container on the host file system?

**Comment by capi** [comment]
@pfmsny I have not yet tried it yet, it was just a general remark on using `encfs`. I'll try it out soon to verify if it will actually work. I use bind-mounts instead of volumes, so it should work. I'll report back once I actually tried.

**Comment by pfmsny** [comment]
Great thanks. I tried a bind mount, but ended up getting permissions errors from Dovecot for user group 5000:5000 from what I recall. Postfix didn't seem to have any issues with it. I may reattempt, it would be a great feature to add to the default container.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
