### ISSUE TITLE
connect to mail.bupt.edu.cn[/var/run/dovecot/lmtp]: No such file or directory

### ISSUE THREAD

**Issue by myheed** [tomav/docker-mailserver#961]
`Apr 24 06:52:32 mail postfix/lmtp[9228]: AAF3C301D8E: to=<sunzhuo@bupt.edu.cn>, relay=none, delay=556, delays=556/0.01/0/0, dsn=4.4.1, status=deferred (connect to mail.bupt.edu.cn[/var/run/dovecot/lmtp]: No such file or directory)
`
What's wrong with it?

**Comment by pfmsny** [comment]
Looks like a LMTP configuration issue. You should post your .yaml and .env configs.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, open a PR based on the current master branch so we can review it.
