### ISSUE TITLE
Cannot use letsencrypt

### ISSUE THREAD

**Issue by Eriton33** [tomav/docker-mailserver#966]
I am running a server with the letsencrypt nginx proxy companion which also created the certificates.

The instructions say to use the letsencrypt certs I have to "mount your whole letsencrypt folder to /etc/letsencrypt". However since the nginx companion does not create a letsencrypt folder with the same structure (no live folder etc.) I cannot use the automatic configuration.

However even using the manual ssl config results in postfix and dovecot using self signed certs for some reason.

My .env file incudes:

SSL_TYPE=manual
SSL_CERT_PATH=/etc/letsencrypt/mydomain.tld/fullchain.pem
SSL_KEY_PATH=/etc/letsencrypt/mydomain.tld/privkey.pem

The cert file includes mydomain.tld, www.maydomain.tld and mail.mydomain.tld

Yet when I take a look into the container:

smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key

ssl_cert = </etc/dovecot/ssl/dovecot.pem
ssl_key = </etc/dovecot/ssl/dovecot.key

How can I find out why a self signed cert was generated anyway?

**Comment by johansmitsnl** [comment]
I have a mount like this: `- ./certs:/etc/letsencrypt/live`

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
