### ISSUE TITLE
I can not receive the email, after I started the container.

### ISSUE THREAD

**Issue by moonshineBoy** [tomav/docker-mailserver#997]
I can not receive the email, after I started the container.

## Context

I follow the `README.md` for install the docker-mailserver to docker, and I also started the docker-mailserver with `docker-compose up -d mail`.

My settings is:

```
HOSTNAME=mail
DOMAINNAME=25.cc
CONTAINER_NAME=mail
```

and I also generated a `xxxserver@25.cc` email.

When I use my gmail send email to the `xxxserver@25.cc`.

## Expected Behavior

I want it send success.

## Actual Behavior

But there did not send success, says there is no `xxxserver@25.cc` address.

### env

My server is CentOS7.2, and docker version is `1.13`.

**Comment by johansmitsnl** [comment]
Is the 25.cc the read domain?
If so, no MX records are setup or IP settings.

**Comment by liaodalin19903** [comment]
no, its 24.hk

**Comment by ToKaTpoHb** [comment]
I have the same problem. Looks like docker-compose dont want to bind to 25 port

**Comment by johansmitsnl** [comment]
@ToKaTpoHb Notice the double quotes on the port: https://github.com/tomav/docker-mailserver/blob/9b7cf1d25bcf224e36b36b8b2e9493516327cf91/docker-compose.yml.dist#L9

**Comment by ToKaTpoHb** [comment]
@johansmitsnl It does not matter. However, here is a few steps to debug this problem (@moonshineBoy  its for you).

1. Check output of `netstat -tulpn` (or similar tool, because i dont know how about centos, but in ubuntu  its present). If you missing this tool, just google how to see open ports. You should be able to see that 25 is open and listened by something.
2. If port is being listen by docker, check output of `docker-compose ps`, and verify that in ports column you have something like 0.0.0.0:25->25/tcp.
3. If you see just 25/tcp, remove container with `docker-compose stop mail && docker-compose rm mail` and start him again with `docker-compose up -d`.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.
